INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000901', N'1 Chu Văn An', N'546 Ngô Gia Tự', 1, 1, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000902', N'1 Lê Quý Đôn', N'92 Nguyễn Đình Chiểu', 1, 1, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000903', N'1 Tiếng Hoa', N'66 Hải Thượng Lãn Ông', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000905', N'1 Tôn Đức Thắng', N'37/3 - 37/5 Ngô Tất Tố', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000909', N'Trung tâm Bảo trợ - Dạy nghề và Tạo việc làm Thành phố', N'215 Võ Thị Sáu', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000911', N'Trung tâm huấn luyện và thi đấu TDTT', N'43 Điện Biên Phủ', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000912', N'Trung tâm Giáo dục phổ thông Đại học Công nghiệp Thực phẩm', N'12 Nguyễn Văn Bảo', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000914', N'1 Gia Định', N'Số 29 đường 13', 1, 1, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000918', N'1 Thanh Niên Xung Phong', N'189e Đặng Công Bỉnh Ấp 5', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79000920', N'BTVH Nhạc viện Tp Hồ Chí Minh', N'112 Nguyễn Du', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760901', N'TT GDNN-GTDX Quận 1', N'16A Nguyễn Thị Minh Khai', 1, 1, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761901', N'TT GDNN-GDTX Quận 12', N'2 Bis Đường Tô Ký Khu phố 3', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762901', N'2 Quận Thủ Đức', N'153/1 Võ Văn Ngân', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763901', N'TT GDNN-GDTX Quận 9', N'Đường Đình Phong Phú', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764901', N'2 Quận Gò Vấp', N'11/3B Phạm Văn Chiêu', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765901', N'TT GDNN-GDTX Quận Bình Thạnh', N'801/19 Tầm Vu', 1, 1, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766901', N'TT GDNN-GDTX Quận Tân Bình', N'95/55 TRƯỜNG CHINH PHƯỜNG 12 QUẬN TÂN BÌNH. TP.HỒ CHI MINH.', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767901', N'TT GDNN-GDTX Quận Tân Phú', N'78/2/45 Phan Đình Phùng', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768901', N'TT GDNN-GDTX Quận Phú Nhuận', N'109 Phan Dang Luu', 1, 2, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769901', N'TT GDNN-GDTX Quận 2', N'45 Phan Bá Vành', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770901', N'TT GDNN-GDTX Quận 3', N'204 Lý Chính Thắng', 1, 1, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771901', N'2 Quận 10', N'461-467 Lê Hồng Phong', 1, 2, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772901', N'TT GDNN-GDTX Quận 11', N'133-135 Nguyễn Chí Thanh (nối dài)', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773901', N'TT GDNN-GDTX Quận 4', N'64 - 66 Nguyễn Khoái Phường 2 Quận 4 Tp. Hồ Chí Minh-Cơ sở 1', 1, 2, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774901', N'TT GDNN-GDTX Quận 5', N'Số 770 Nguyễn Trãi', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775901', N'TT GDNN-GDTX Quận 6', N'743/15 Hồng Bàng', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776901', N'TT GDNN-GDTX Quận 8', N'3-5 Huỳnh Thị Phụng', 1, 2, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777901', N'TT GDNN-GDTX Quận Bình Tân', N'31A Hồ Học Lãm', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778901', N'TT GDNN-GDTX Quận 7', N'27/3 Khu phố 3 Đường số 10 -P.Bình Thuận -Quận 7', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783901', N'TT GDNN-GDTX Huyện Củ Chi', N'Khu Phố 3 - Thị Trấn Củ Chi - Huyện Củ Chi', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784901', N'TT GDNN-GDTX Huyện Hóc Môn', N'65 Đỗ Văn Dậy Tân Thới 1 xã Tân Hiệp Huyện Hóc Môn', 1, 2, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785901', N'TT GDNN-GDTX Huyện Bình Chánh', N'A13/9 đường Nguyễn Hữu Trí khu phố 1 thị trấn Tân Túc huyện Bình Chánh tp. Hồ Chí Minh', 1, 2, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786901', N'TT GDNN-GDTX Huyện Nhà Bè', N'5/19 A đường Nguyễn Bình Ấp 1', 1, 0, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787901', N'TT GDNN-GDTX Huyện Cần Giờ', N'Đường Lương Văn Nho khu phố Giồng Ao thị trấn Cần Thạnh huyện Cần Giờ thành phố Hồ Chí Minh', 1, 0, 0, N'SGD&DT HCM');
