INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760401', N'TH Hòa Bình', N'Số 01 Công Xã Paris', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760402', N'TH Kết Đoàn', N'2B Lương Hữu Khánh', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760403', N'TH Đinh Tiên Hoàng', N'67 Đinh Tiên Hoàng', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760404', N'TH Lê Ngọc Hân', N'12 Sương Nguyệt Anh', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760406', N'TH Chương Dương', N'296 Bis Bến Chương Dương', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760407', N'TH Trần Hưng Đạo', N'81 Trần Đình Xu', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760408', N'TH Khai Minh', N'44 Phó Đức Chính', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760409', N'TH Nguyễn Thái Học', N'71 Trần Hưng Đạo', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760410', N'TH Nguyễn Thái Bình', N'105 Nguyễn Thái Bình', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760411', N'TH Trần Khánh Dư', N'53/61 Trần Khánh Dư', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760412', N'TH Trần Quang Khải', N'68/29B Trần Quang Khải', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760413', N'TH Phan Văn Trị', N'43 Phạm Viết Chánh', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760414', N'Tiểu học Nguyễn Bỉnh Khiêm', N'2 Bis Nguyễn Bỉnh Khiêm phường Bến Nghé quận Bình Thạnh', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760415', N'Tiểu học Đuốc Sống', N'2 Đinh Công Tráng', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760416', N'TH Nguyễn Huệ', N'93-95A Lê Thị Riêng', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79760418', N'TH Lương Thế Vinh', N'116 Cô Giang', 1, 3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'70123015', N'Tiểu học Nam Việt', NULL, 2, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761401', N'TH Phạm Văn Chiêu', N'2683/1A Kp1', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761402', N'TH Quang Trung', N'17b Kp4', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761403', N'TH Hà Huy Giáp', N'84/1 Khu Phố 1', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761404', N'TH Nguyễn Du', N'A36bis Kp1', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761405', N'TH Nguyễn Khuyến', N'30/A1 Kp1A', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761406', N'TH Trần Văn Ơn', N'78/4a bis-KP7Trường Chinh', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761407', N'TH Quới Xuân', N'219/4 Kp5', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761408', N'TH Nguyễn Văn Thệ', N'326 Hà Huy Giáp Kp3', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761409', N'TH Nguyễn Thị Minh Khai', N'11at1 Khu Phố 1 Phường Tân Thới Nhất Quận 12', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761410', N'TH Thuận Kiều', N'62/14b Kp6', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761411', N'TH Lê Văn Thọ', N'225 Kp4 đường Nguyễn Thị Kiểu P.Tân Thới Hiệp Quận 12 TP.HCM', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761412', N'TH Trần Quang Cơ', N'Kp3', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761413', N'TH Hồ Văn Thanh', N'24/1.kp6', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761414', N'TH Kim Đồng', N'Số 1 Đường Số 2', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761415', N'Tiểu học Nguyễn Trãi', N'170/4A Kp1', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761416', N'TH Võ Văn Tần', N'Khu phố 5', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761418', N'TH Trương Định', N'Khu Phố 4', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761419', N'TH Thần Đồng', N'229/1/1 A', 2, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761420', N'Tiểu học Nguyễn Thị Định', N'TTN01  -  Khu Phố 3', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761421', N'TH Nguyễn Thái Bình', N'Số 21 Đường HT 11 Kp3 Phường Hiệp Thành Quận 12', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761422', N'Tiểu học Lý Tự Trọng', N'112/30 khu phố 5', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761423', N'TH Võ Thị Sáu', N'Khu phố 3', 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79761424', N'TH Võ Thị Thừa', NULL, 1, 3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762401', N'TH Nguyễn Trung Trực', N'962 Kha Vạn Cân', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762402', N'TH Lương Thế Vinh', N'1 Dân Chủ- KP2- phường Bình Thọ- Quận Thủ Đức- TP Hồ Chí Minh', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762404', N'TH Bình Triệu', N'144/12 Quốc Lộ 13 KP2', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762405', N'TH Đặng Thị Rành', N'137 Quốc Lộ 13 cũ  Kp3', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762406', N'TH Hiệp Bình Phước', N'630 Quốc Lộ 13', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762407', N'TH Thái Văn Lung 1', N'93/6 Tam Châu Kp5', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762408', N'TH Tam Bình', N'71 đường 10 Khu phố 3', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762409', N'TH Trần Văn Vân', N'15 đường 11 Kp4', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762410', N'TH Bình Chiểu', N'902 tỉnh lộ 43 kp1 p.Bình Chiểu', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762411', N'TH Xuân Hiệp', N'Linh Xuân', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762412', N'Tiểu học Hoàng Diệu', N'33 Lê Văn Chí Kp3', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762413', N'TH Nguyễn Văn Triết', N'57 Hoàng Diệu Kp2', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762414', N'Tiểu học Linh Tây', N'16/5 Kp2', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762415', N'TH Bình Quới', N'18/18 Đường 22 Kp4', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762416', N'TH Đặng Văn Bất', N'30/6 Đường 35 Kp2', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762417', N'Tiểu Học Linh Đông', N'170 Tô Ngọc Vân', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762418', N'TH Nguyễn Văn Banh', N'7/9a Kp5', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762419', N'TH Hiệp Bình Chánh', N'29 đường1 Khu phố 5', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762420', N'TH Từ Đức', N'6 Đường Đoàn Kết Kp3', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762421', N'TH Trương Văn Hải', N'76  Phú Châu', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762422', N'TH Nguyễn Văn Lịch', N'Số 66 Đường 6 Kp3', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762423', N'TH Đào Sơn Tây', N'61 Hiệp Bình', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762424', N'TH Linh Chiểu', NULL, 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762427', N'TH Đỗ Tấn Phong', N'103 đường Lê Văn Chí Kp 3', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762428', N'TH Nguyễn Văn Tây', N'Đường số 4 khu phố 2 P.Bình Chiểu Q.Thủ Đức', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79762429', N'TH Nguyễn Văn Nở', N'Số 12 đường 10 Khu phố 3', 1, 3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763401', N'TH Long Bình', N'Khu Tái Định Cư Phước Thiện Phường Long Bình Q9', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763402', N'TH Phước Bình', N'Đường 18', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763403', N'TH Tạ Uyên', N'Khu tái định cư Long Sơn', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763404', N'TH Đinh Tiên Hoàng', N'Lê LợiKp2 P.Hiệp PhúQ9', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763405', N'TH Phú Hữu', N'Kp4 Đường 898 P.phú Hữu Q.9 Tp HCM', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763406', N'TH Võ Văn Hát', N'Kp5 Đỗ Xuân Hợp Phường Phước Long B Quận 9 TPHCM', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763407', N'TH Long Thạnh Mỹ', N'35 đường 20 Kp1 Phường Long Thạnh Mỹ Quận 9.', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763408', N'TH Hiệp Phú', N'Kp4 P. Hiệp Phú Q9', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763409', N'TH Nguyễn Minh Quang', N'284 Hoàng Hữu Nam Giãn Dân', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763410', N'TH Phước Thạnh', N'26 Nguyễn Duy Trinh Phước Lai', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763411', N'TH Trương Văn Thành', N'Kp3 Lã Xuân Oai', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763412', N'Tiểu học Phong Phú', N'Khu phố 3Phường Tăng Nhơn Phú B Quận 9', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763413', N'TH Long Phước', N'Ấp Long Thuận', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763414', N'TH Bùi Văn Mới', N'Đường Hồ Bá Phấn Kp4', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763415', N'TH Trường Thạnh', N'Số 1 Đường 3 Kp Phước hiệp', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763417', N'TH Tân Phú', N'Số 7 Đường 138.Khu phố 2.Phường Tân Phú. Quận 9.TpHCM', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763419', N'TH Lê Văn Việt', N'KP1  Man Thiện', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763420', N'TH Nguyễn Văn Bá', N'Đường 359 Khu Phố 5', 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763421', N'TH Trần Thị Bưởi', NULL, 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79763422', N'TH Phạm Văn Chính', NULL, 1, 3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764401', N'TH Nguyễn Thượng Hiền', N'36 Nguyễn Thượng Hiền Phường 1 Quận Gò Vấp', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764402', N'TH Trần Văn Ơn', N'90 Nguyễn Thái Sơn', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764403', N'Tiểu học Phạm Ngũ Lão', N'Số 5 Phạm Ngũ Lão', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764404', N'TH Hanh Thông', N'5 Lê Lợi', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764405', N'TH Nguyễn Viết Xuân', N'332A Dương Quảng Hàm', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764407', N'TH Trần Quốc Toản', N'Cơ sở 1: A20 Phan Văn Trị Phường 7 Gò Vấp TPHCM
Cơ sở 2: 18/183 Nguyễn Du Phường 7 Gò Vấp TPHCM', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764408', N'TH Kim Đồng', N'1A Quang Trung phường 10 quận Gò Vấp', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764409', N'TH Nguyễn Thị Minh Khai', N'31/1c Quang Trung', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764410', N'TH Chi Lăng', N'645/2 Quang Trung', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764411', N'TH An Hội', N'2 Phạm Văn Chiêu', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764412', N'TH Lam Sơn', N'11/3B Phạm Văn Chiêu', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764413', N'TH Lê Thị Hồng Gấm', N'54/11 Phạm Văn Chiêu', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764414', N'TH Lương Thế Vinh', N'Số 02 đường 13', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764415', N'TH Lê Hoàn', N'11/214A Lê Đức Thọ', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764416', N'TH Phan Chu Trinh', N'40/25A Thống Nhất', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764417', N'TH Võ Thị Sáu', N'450/19A Lê Đức Thọ', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764418', N'TH Trần Quang Khải', N'197/2 Nguyễn Văn Lượng P.17 Q.GV Tp.HCM', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764419', N'TH Hoàng Văn Thụ', N'161/807E Nguyễn Oanh', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764420', N'TH Nhựt Tân', N'Số 3 đường số 9', 2, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764421', N'TH Lê Quý Đôn', N'237/63 Phạm Văn Chiêu', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764422', N'TH Việt Mỹ', N'982/8 đường Quang Trung', 2, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764423', N'TH Lê Đức Thọ', N'688/57/44 Đường Lê Đức Thọ', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79764424', N'TH Lê Văn Thọ', N'1115 Lê Đức Thọ Phường 13 Quận Gò Vấp', 1, 3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765401', N'Tiểu học Tô Vĩnh Diện', N'26 Vũ Tùng P1 BT', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765402', N'TH Lam Sơn', N'280 Bùi Hữu Nghĩa', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765403', N'TH Hà Huy Tập', N'7A Phan Đăng Lưu', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765404', N'Tiểu học Yên Thế', N'377 Lê Quang Định P.5 Q.Bình Thạnh', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765405', N'TH Nguyễn Bá Ngọc', N'47/55 Nguyễn Văn Đậu', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765406', N'Tiểu học Bế Văn Đàn', N'9/1 B Hoàng Hoa Thám p6 QBT', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765407', N'TH Phan Văn Trị', N'348 Phan Văn Trị', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765408', N'TH Bình Hòa', N'01 Chu Văn An', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765409', N'TH Trần Quang Vinh', N'555 Bùi Đình Túy', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765410', N'TH Bình Lợi Trung', N'138A Nơ Trang Long', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765411', N'TH Nguyễn Đình Chiểu', N'1B Lê Quang Định', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765412', N'TH Lê Đình Chinh', N'241 Điện Biên Phủ', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765413', N'TH Hồng Hà', N'155A Xô Viết Nghệ Tĩnh', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765414', N'TH Phù Đổng', N'22B Xô Viết Nghệ Tĩnh', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765415', N'TH Thạnh Mỹ Tây', N'10 Phạm Viết Chánh', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765416', N'TH Nguyễn Trọng Tuyển', N'Hẻm 294 Xô Viết Nghệ Tĩnh', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765417', N'TH Cửu Long', N'A 19/12  Ngô Tất Tố', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765418', N'Trường Tiểu học Đống Đa', N'1B Điên Biên Phủ', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765419', N'TH Chu Văn An', N'Số 2 đường 3 CX Chu Văn An', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765420', N'TH Tầm Vu', N'69/3 Xô Viết Nghệ Tĩnh', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765421', N'TH Thanh Đa', N'Khu 2 Cư Xá Thanh Đa', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765423', N'TH Bạch Đằng', N'72/7 Bạch Đằng P.24', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765426', N'TH Việt Mỹ', N'2.2-2.3 Đường 12AB KDC Miếu Nổi', 2, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765428', N'TH Ngôi Nhà Thông Thái', N'195/15 Điện Biên Phủ', 2, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79765429', N'Trường Tiểu học Bình Quới Tây', N'376 Bình Quới', 1, 3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766401', N'TH Lê Văn Sĩ', N'322 Nguyễn Trọng Tuyển', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766402', N'TH Tân Sơn Nhất', N'62 Thăng Long', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766403', N'TH Nguyễn Thanh Tuyền', N'19 Bùi Thị Xuân', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766405', N'TH Bình Giã', N'154/321 Phạm Văn Hai', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766406', N'TH Hoàng Văn Thụ', N'55 Hoàng Việt', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766407', N'TH Phạm Văn Hai', N'370A Phạm Văn Hai', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766408', N'TH Bạch Đằng', N'7 Cách Mạng Tháng Tám', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766409', N'TH Chi Lăng', N'09 Khai Tríphường 06 Q.Tân Bình TPHCM', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766410', N'TH Đống Đa', N'1 Đất Thánh', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766411', N'TH Bành Văn Trân', N'123 Bành Văn Trân', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766413', N'Tiểu học Trần Văn Ơn', N'54 Duy Tân phường 8 quận tân Bình', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766415', N'TH Ngọc Hồi', N'373/1/145 Lý Thường Kiệt', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766416', N'TH Phú Thọ Hoà', N'550/2 Âu Cơ', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766417', N'TH Lê Thị Hồng Gấm', N'624/21 Âu Cơ - Phường 10 - Quận Tân Bình', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766418', N'TH Nguyễn Văn Trỗi', N'25/1 Tái Thiết', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766419', N'TH Lạc Long Quân', N'947/12 Lạc Long Quân', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766420', N'TH Cách Mạng Tháng Tám', N'69 Trường Chinh', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766421', N'Tiểu học Nguyễn Khuyến', N'74 Trần Mai Ninh', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766422', N'TH Trần Quốc Tuấn', N'19 Cộng Hòa', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766423', N'Trường tiểu học Trần Quốc Toản', N'114 Đồng Đen', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766424', N'TH Yên Thế', N'31 Núi Thành', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766425', N'TH Sơn Cang', N'42/2A Văn Chung', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766426', N'Tiểu học Tân Trụ', N'100 Nguyễn Phúc Chu', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766432', N'TH Nguyễn Văn Kịp', N'45/33 Trần Thái Tông', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766434', N'TH TT Lương Thế Vinh', N'481/9 Trường Chinh', 2, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766435', N'TH Thân Nhân Trung', N'83 Nguyễn Đức Thuận', 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79766S10', N'TH Phan Huy Ích', NULL, 1, 3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767401', N'TH Đoàn Thị Điểm', N'16 Trần Văn Ơn', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767402', N'Tiểu học Lê Lai', N'150 đường Tây Thạnh', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767403', N'TH Tô Vĩnh Diện', N'51/8 Đô Đốc Lộc', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767405', N'TH Lê Văn Tám', N'145 Độc Lập', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767406', N'TH Phan Chu Trinh', N'193A Thạch Lam', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767407', N'TH Duy Tân', N'39B Lương Trúc Đàm', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767408', N'TH Võ Thị Sáu', N'343 Nguyễn Sơn Phú Thạnh', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767409', N'TH Hồ Văn Cường', N'51-53 Trịnh Đình Trọng', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767410', N'TH Huỳnh Văn Chính', N'39 Huỳnh Thiện Lộc', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767411', N'TH Âu Cơ', N'23/15 Trần Văn Cẩn', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767413', N'TH Tân Hương', N'167/29 Tân Quý P Tân Quý', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767416', N'TH Tân Sơn Nhì', N'905/4 Âu Cơ P.Tân Sơn Nhì', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767417', N'TH Hiệp Tân', N'252/16 Phan Anh', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767419', N'Tiểu học Tân Thới', N'61 Đỗ Thừa Luông', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767420', N'TH Tân Hóa', N'58/29 Lũy Bán Bích Phường Tân Thới Hòa Quận Tân Phú', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767421', N'TH Đinh Bộ Lĩnh', N'91B Bờ Bao Tân Thắng P. Sơn Kỳ Q. Tân Phú', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79767422', N'TH Lê Thánh Tông', N'197199 Đường Trịnh Đình Trọng Phường Phú TRung Quận Tân Phú TP.HCM', 1, 3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768401', N'Tiểu học Sông Lô', N'413 Phan Xích Long', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768402', N'Cổ Loa', N'L6A cư xá Nguyễn Đình Chiểu', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768403', N'Cao Bá Quát', N'92 Phan Đăng Lưu', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768404', N'Đông Ba', N'99 Phan Đăng Lưu', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768406', N'TH Đặng Văn Ngữ', N'35 Đặng Văn Ngữ', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768407', N'Vạn Tường', N'15 Hồ Biểu Chánh', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768408', N'Nguyễn Đình Chính', N'93-95 Nguyễn Văn Trỗi', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768409', N'Chí Linh', N'525/73Huỳnh Văn Bánh', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768410', N'TH Phạm Ngọc Thạch', N'175 Đặng Văn Ngữ', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768411', N'Trung Nhất', N'243/3 Phan Đình Phùng', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768412', N'TH Lê Đình Chinh', N'73/1 Hoàng Văn Thụ', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79768414', N'Tiểu học Hồ Văn Huê', N'9 Hoàng Minh Giam', 1, 3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769401', N'TH An Khánh', N'Số 2 Đường 9', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769403', N'TH An Phú', N'Khu Dân Cư Sông Giồng Kp2', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769404', N'TH Giồng Ông Tố', N'159 đường 6 Kp4', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769405', N'TH Huỳnh Văn Ngỡi', N'78 Quốc Hương Phường Thảo Điền Quận 2.
722 Nguyễn Đăng Giai Phường Thảo Điền Quận 2', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769406', N'TH Mỹ Thủy', N'24 đường 68 Khu dân cư Cát Lái Phường Cát Lái Quận 2', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769407', N'TH Nguyễn Văn Trỗi', N'số 6 đường A4 Kp3', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769408', N'TH Thạnh Mỹ lợi', N'668 Nguyễn Thị Định', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769409', N'TH Nguyễn Hiền', N'37 Trần Lựu', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769410', N'TH Lương Thế Vinh', N'215 Trương Văn Bang', 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769412', N'TH An Bình', NULL, 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769413', N'TH Bình Trưng Đông', NULL, 1, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769514', N'TH Trường Anh', NULL, 2, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79769515', N'QT Ngôi Sao Sài Gòn', NULL, 2, 3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770403', N'TH Kỳ Đồng', N'24 Kỳ Đồng', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770404', N'TH Mê Linh', N'159 Hai Bà Trưng', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770406', N'TH Lương Định Của', N'576 Nguyễn Đình Chiểu Phường 4 Quận 3', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770407', N'TH Nguyễn Sơn Hà', N'55A Cao Thắng', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770408', N'TH Nguyễn Thái Sơn', N'12 Huỳnh Tịnh Của', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770409', N'TH Nguyễn Thanh Tuyền', N'183 Nam Kỳ Khởi Nghĩa', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770410', N'TH Nguyễn Thi', N'448/12 Lê Văn Sỹ', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770411', N'TH Nguyễn Thiện Thuật', N'633/36 Điện Biên Phủ', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770412', N'TH Nguyễn Việt Hồng', N'292/9 Cách Mạng Tháng 8', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770413', N'TH Phan Đình Phùng', N'491/7 Nguyễn Đinh Chiểu', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770414', N'Tiểu học Phan Văn Hân', N'382/26 Nguyễn Thị Minh Khai', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770417', N'TH Trần Quang Diệu', N'388 Lê Văn Sỹ', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770418', N'TH Trần Quốc Thảo', N'6 Võ Văn Tần', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770419', N'TH Trần Văn Đang', N'205/39/15 Trần Văn Đang', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770420', N'TH Trương Quyền', N'946 Trường Sa P.13 Q.3', 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79770422', N'TH Thực hành Đại học Sài Gòn', NULL, 1, 3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771401', N'TH Hồ Thị Kỷ', N'105 Hồ Thị Kỷ', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771402', N'TH Trần Nhân Tôn', N'247 Hòa Hảo', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771403', N'TH Trương Định', N'382 Sư Vạn Hạnh', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771405', N'TiH Trần Quang Cơ', N'438 Ngô Gia Tự', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771406', N'TH Nguyễn Chí Thanh', N'302 Nguyễn Chí Thanh P5 Q10', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771407', N'TH Dương Minh Châu', N'34 Nguyễn Lâm', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771408', N'TH Nhật Tảo', N'1 Nhật Tảo', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771409', N'TH Điện Biên', N'594/1 Điện Biên Phủ', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771410', N'TH Thiên Hộ Dương', N'157 Tô Hiến Thành', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771411', N'TH Triệu Thị Trinh', N'91/8D Hòa Hưng', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771412', N'TH Hoàng Diệu', N'283/44-46 CMT8', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771413', N'TH Lê Thị Riêng', N'hẻm 493 Cách Mạng Tháng 8', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771414', N'TH Lê Đình Chinh', N'7/4 Thành Thái', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771415', N'TH Bắc Hải', N'103-105 Bắc Hải Phường 15 Quận 10', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771416', N'TH Tô Hiến Thành', N'104 Đường Tô Hiến Thành', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771417', N'TH Võ Trường Toản', N'354/74 Lý Thường Kiệt Phường 14 Quận 10', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79771420', N'TH Trần Văn Kiểu', N'479 Vĩnh ViễnP7Q10', 1, 3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772401', N'TH Hưng Việt', N'135 Lạc Long Quân', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772402', N'TH Nguyễn Thi', N'1484 Đường Ba Tháng Hai', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772403', N'TH Phạm Văn Hai', N'888-890 Nguyễn Chí Thanh', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772404', N'TH Hòa Bình', N'66 Hòa Bình', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772405', N'TH Trần Văn Ơn', N'612 Lạc Long Quân', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772406', N'Tiểu học Âu Cơ', N'160B Trần Quý', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772407', N'TH Đề Thám', N'10 Lê Đại Hành', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772408', N'TH Lạc Long Quân', N'225 Lò Siêu', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772409', N'TH Hàn Hải Nguyên', N'137-139 Thái Phiên', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772410', N'TH Nguyễn Bá Ngọc', N'395/9G Minh Phụng', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772411', N'TH Thái Phiên', N'393BC Minh Phụng', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772412', N'TH Phùng Hưng', N'250 Lạc Long Quân', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772413', N'TH Quyết Thắng', N'391 Lê Đại Hành P11 Q11', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772414', N'TH Phú Thọ', N'322 Tôn Thất Hiệp', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772415', N'TH Đại Thành', N'79/22 Âu Cơ', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772416', N'TH Trưng Trắc', N'160 Nguyễn Thị Nhỏ ( nối dài)', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772417', N'TH Lê Đình Chinh', N'203 Nguyễn Thị Nhỏ P16 Q11', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772420', N'TH Việt Mỹ Úc', N'45 Đường Số 5 Cư Xá Bình Thới', 2, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772421', N'TH Bình Thới', N'181/23-27-29 Bình Thoi', 2, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772422', N'TH 3 Việt Mỹ', N'252 Lạc Long Quân', 2, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79772423', N'Tiểu học Nguyễn Thị Nhỏ', N'Số 1 đường Nội Bộ C Khu Chung Cư Phú Thọ', 1, 3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773401', N'TH Nguyễn Huệ 1', N'91B Nguyễn Khoái', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773402', N'TH Đoàn Thị Điểm', N'140 Nguyễn Khoái', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773403', N'Tiểu học Lê Thánh Tôn', N'209/71 Tôn Thất Thuyết', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773404', N'TH Vĩnh Hội', N'183C/3 Tôn Thất Thuyết Phường 4 Quận 4 Thành phố Hồ Chí Minh', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773405', N'TH Đặng Trần Côn', N'202-203 Bến Vân Đồn', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773406', N'TH Lý Nhơn', N'I28 Bến Vân Đồn', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773408', N'TH Bạch Đằng', N'57 Lê Quốc Hưng P.12', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773409', N'Tiểu học Bến Cảng', N'298B Nguyễn Tất Thành', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773410', N'Tiểu học Xóm Chiếu', N'Số 9 Tôn Đản', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773411', N'TH Đống Đa', N'177/7 Tôn Thất Thuyết', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773413', N'TH Đinh Bộ Lĩnh', N'92b/20bis Tôn Thất Thuyết', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773414', N'TH Nguyễn Trường Tộ', N'181/17 Xóm Chiếu', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773415', N'TH Nguyễn Thái Bình', N'2 Tôn Thất Thuyết', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773416', N'TH Nguyễn Văn Trỗi', N'02 Vĩnh Khánh', 1, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79773417', N'TH Anh Việt Mỹ', N'298A Nguyễn Tất Thành', 2, 3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774401', N'TH Hàm Tử', N'750-752 Võ Văn Kiệt', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774402', N'TH Trần Bình Trọng', N'120 Trần Bình Trọng', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774403', N'TH Huỳnh Mẫn Đạt', N'5 Huỳnh Mẫn Đạt', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774404', N'TH Bàu Sen', N'106 Nguyễn Trãi', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774405', N'Tiểu học Lê Văn Tám', N'144 Trần Phú', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774406', N'TH Chương Dương', N'91-93 Nghĩa Thục', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774407', N'TH Huỳnh Kiến Hoa', N'16 - 18 Nguyễn Văn Đừng', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774408', N'Tiểu học Phạm Hồng Thái', N'38 Nguyễn Duy Dương', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774409', N'TH Trần Quốc Toản', N'292 Trần Phú', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774410', N'Tiểu Học Lý Cảnh Hớn', N'02  Xóm Chỉ', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774411', N'TH Chính Nghĩa', N'676 Nguyễn Trãi', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774412', N'TH Minh Đạo', N'15 Ký Hòa', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774413', N'TH Nguyễn Viết Xuân', N'768 Nguyễn Trãi', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774414', N'TH Lê Đình Chinh', N'8-15 Vạn Tượng', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774415', N'TH Nguyễn Đức Cảnh', N'25 Học Lạc', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79774416', N'Tiểu học Hùng Vương', N'266 Hồng Bàng', 1, 3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775401', N'TH Phạm Văn Chí', N'634 Phạm Văn Chí', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775402', N'TH Trương Công Định', N'205/42/2 Tân Hòa Đông', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775403', N'TH Phú Định', N'15 Lý Chiêu Hoàng', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775404', N'TH Kim Đồng', N'1526 Võ Văn Kiệt', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775405', N'TH Phù Đổng', N'Số 2 đường số 9 P11 Q6', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775406', N'TH Nguyễn Huệ', N'178 Gia Phú Phường 1 Quận 6', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775407', N'TH Him Lam', N'63 Đường Số 11 Cư Xá Đài Rađa', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775408', N'TH Chi Lăng', N'199/31 Lê Quang Sung', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775409', N'TH Phú Lâm', N'Số 6 Tân Hòa Đông', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775410', N'Tiểu học CHÂU VĂN LIÊM', N'157 Phan Văn Khỏe', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775411', N'TH Lam Sơn', N'820/25 Hậu Giang', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775412', N'TH Lê Văn Tám', N'30/4 Nguyễn Đình Chi', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775413', N'TH Nhật Tảo', N'206 Phạm Văn Chí', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775414', N'TH Võ Văn Tần', N'97 Phạm Đình Hổ', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775415', N'TH Nguyễn Thiện Thuật', N'100 Phan Văn Khỏe', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775416', N'TH Bình Tiên', N'260 264 Phan Văn Khỏe', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775418', N'TH Vĩnh Xuyên', N'63 Chu Văn An', 2, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775420', N'TH Hùng Vương', N'660-662 Phạm Văn Chí', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775422', N'TH Nguyễn Văn Luông', N'489B/6 Hậu Giang', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79775423', N'TH Đặng Nguyên Cẩn', N'369 Đặng Nguyên Cẩn', 1, 3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776401', N'TH Nguyễn Trực', N'38A Dương Bá Trạc', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776402', N'TH Rạch Ông', N'284 Dương Bá Trạc', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776403', N'Tiểu học Âu Dương Lân', N'79 Âu Dương Lân', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776404', N'TH Vàm Cỏ Đông', N'771-795 Phạm Thế Hiển', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776405', N'TH Thái Hưng', N'785 Tạ Quang Bửu', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776406', N'TH Bông Sao', N'196 Bùi Minh Trực', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776407', N'Trường Tiểu học Phan Đăng Lưu', N'1755 Phạm Thế Hiển', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776408', N'TH Bùi Minh Trực', N'2225 Phạm Thế Hiển P6q8', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776409', N'TH An Phong', N'lố F1khu dân cư Hai Thành', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776410', N'Tiểu học Trần Danh Lâm', N'68 Hưng Phú', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776411', N'Tiểu học Hưng Phú', N'692 B Hưng Phú', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776413', N'TH Lý Thái Tổ', N'275-307 Bình Đông', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776414', N'TH Tuy Lý Vương', N'381 Tùng Thiện Vương P12 Q8', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776415', N'TH Trần Nguyên Hãn', N'45 Trần Nguyên Hãn', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776416', N'TH Hồng Đức', N'289A Bình Đông', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776417', N'TH Nguyễn Nhược Thị', N'2 Nguyễn Nhược Thị', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776418', N'TH Lưu Hữu Phước', N'145 bis Mễ Cốc P15 Q8', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776419', N'TH Nguyễn Trung Ngạn', N'16 đường 3229 Phạm Thế Hiển', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776420', N'TH Nguyễn Công Trứ', N'4 Trương Đình Hội', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776421', N'TH Lý Nhân Tông', N'575 - 577 Hưng Phú', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776422', N'TH Hoàng Minh Đạo', N'252 Bông Sao', 1, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776424', N'TH Đông Nam Á', NULL, 2, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79776425', N'TH Khai Nguyên', NULL, 2, 3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777401', N'THCL An Lạc 1', N'687/6 Kinh Dương Vương KP3', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777402', N'TH An Lạc 2', N'121 Phùng Tá Chu Kp7', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777403', N'THCL An Lạc 3', N'504/58C Kinh Dương Vươngphường An Lạc AQuận Bình TânTP.Hồ Chí Minh.', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777404', N'THCL Bình Hưng Hòa 1', N'15 Hồ Văn Long KP1', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777405', N'THCL Bình Thuận', N'181 Ấp Chiến Lược Kp3 P. Bình Hưng Hòa A Q. Bình Tân', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777406', N'TH Bình Trị 1', N'620 Hương Lộ 2 Khu phố 6 Phường Bình Trị Đông Quận Bình Tân', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777407', N'THCL Tân Tạo', N'119 Hồ Văn Long Kp3 Phường Tân Tạo Bình Tân', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777408', N'Trường Tiểu học Ngô Quyền', N'118 đường số 3 Kp4', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777409', N'TH Bình Trị 2', N'Số 88A đường số 3 phường Bình Trị Đông B', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777410', N'TH Bình Trị Đông A', N'999 Hương Lộ 2 KP8', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777411', N'THCL Bình Long', N'Số 1A đường số 4 Kp7 P.Bình Hưng Hòa A Q.Bình Tân', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777412', N'THCL Lê Công Phép', N'Số 01 Đường Số 1a Khu Phố 6 Phường An Lạc Quận Bình Tân TP Hồ Chí Minh', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777413', N'THCL Bình Trị Đông', N'276/68 Tân Hòa Đông Phường Bình Trị Đông Quận Bình Tân', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777414', N'TH Bình Tân', N'1-3 Đường 48 khu phố 9 Phường Tân Tạo Quận Bình Tân', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777415', N'TH Tân Tạo A', N'Đường Lộ Tẻ Khu phố 3P.Tân Tạo A', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777416', N'Tiểu học Kim Đồng', N'101 Liên khu 4-5 Khu phố 5', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777417', N'THTT Trí Tuệ Việt', N'Số 79 đường số 3 KDC Vĩnh Lộc Kp4', 2, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777419', N'THCL Lê Trọng Tấn', N'79/24 Đường số 7 Khu Phố 7 Phường Bình Hưng Hòa Quận Bình Tân TP.HCM', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777420', N'TH Phù Đổng', N'73 Lô Tư P.Bình Hưng Hòa A Q.Bình Tân', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777422', N'THCL Bình Hưng Hòa', N'88/2 Đường số 18 Khu Phố 2 Phường Bình Hưng Hòa Quận Bình Tân TP.HCM', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777423', N'TH Trần Văn Ơn', N'160b Hồ Văn Long', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777425', N'THCL Lê Quý Đôn', N'2A/58 Lê Ngung P. Tân Tạo A Q. Bình Tân TpHCM', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79777426', N'TH Lạc Hồng', N'1014/88/11 Đường Tan Kỳ Tân Quý Khu phố 14', 1, 3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778401', N'Tiểu học Phan Huy Thực', N'53/12', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778402', N'TH Lê Quý Đôn', N'239/7 Trần Xuân Soạn', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778403', N'TH Tân Quy', N'217/2 Lê Văn Lương Kp1', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778404', N'TH Lương Thế Vinh', N'Số 12 Đường 10 Kp3', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778405', N'TH Trần Quốc Toản', N'435 Huỳnh Tấn Phát P.Tân Thuận Đông Q7', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778406', N'TH Tân Thuận', N'8/7 Đường Bùi Văn Ba Khu phố 2', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778407', N'TH Phù Đổng', N'36B Lâm Văn Bền Kp4', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778408', N'TH Lê Văn Tám', N's15 Đường Tân Phú P.Tân Phú Q7', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778409', N'TH Đinh Bộ Lĩnh', N'11 đường 53 Nguyễn Thị Thập', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778410', N'TH Nguyễn Văn Hưởng', N'1207 Huỳnh Tấn Phát', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778411', N'TH Lê Anh Xuân', N'23 đường Phú Thuận Kp22', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778412', N'TH Phú Mỹ', N'76/5 Phạm Hữu Lầu', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778413', N'TiH Nguyễn Thị Định', N'203 Lâm Văn Bền', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778415', N'TH Kim Đồng', N'Nguyễn Văn Linh Kp1', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778416', N'TH Nam Sài Gòn', N'Khu A Đô Thị Mới Nam Sài Gòn', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778417', N'TH Đặng Thùy Trâm', N'215 Trần Xuân Soạn', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778418', N'TH Võ Thị Sáu', N'Lô R6 Đặng Đại Độ', 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778419', N'TH Phạm Hữu Lầu', NULL, 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79778420', N'TH Phú Thuận', NULL, 1, 3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783401', N'TH Tân Phú', N'Ấp Xóm Đồng', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783402', N'TH Tân Phú Trung', N'Ấp Đình', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783403', N'TH Tân Thông Hội', N'Ấp Hậu', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783404', N'TH Tân Tiến', N'61 Trần Tử Bình Ấp Tân Tiến', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783405', N'TH Lê Thị Pha', N'Ấp Hậu', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783406', N'TH Nguyễn Văn Lịch', N'Ấp Mũi Lớn 2', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783407', N'TH Liên Minh Công Nông', N'Ấp Bàu Tre 2 Đường Nguyễn Thị Rành', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783408', N'TH Thị Trấn Củ Chi', N'Khu phố 1', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783409', N'TH Tân Thành', N'Đường Can Trường khu phố 4 thị trấn Củ Chi', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783410', N'TH Phước Vĩnh An', N'660 Tỉnh Lộ 8 Ấp 4 xã Phước Vĩnh An Huyện Củ Chi TP HCM', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783411', N'TH Trần Văn Chẩm', N'Ấp 5', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783412', N'TH Phước Hiệp', N'Ấp Phước Hòa', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783413', N'TH Phước Thạnh', N'Số 30 Đường 671 Ấp Chợ', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783414', N'TH An Phước', N'Ấp Phước Hưng', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783415', N'TH Thái Mỹ', N'Ấp Bình Thượng 1', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783416', N'TH Lê Văn Thế', N'Ấp Trảng Lắm xã trung lập hạ huyện củ chi', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783417', N'TH Trung Lập Hạ', N'Tỉnh lộ 7 Ấp Đồn', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783419', N'TH Trung Lập Thượng', N'Số 499 đường Trung Lập ấp Đồng Lớn', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783420', N'TH An Nhơn Đông', N'Ấp Gò Nổi', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783421', N'TH An Nhơn Tây', N'Ấp Xóm Trại xã An Nhơn Tây huyện Củ Chi Tp. Hồ Chí Minh', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783422', N'TH An Phú 1', N'Ấp An Hòa', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783423', N'TH An Phú 2', N'Phú Bình An Phú', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783424', N'TH Phú Mỹ Hưng', N'Ấp Phú Lợi', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783425', N'TH Nhuận Đức', N'Ấp Bàu Chứa', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783426', N'TH Nhuận Đức 2', N'Ấp Ngã Tư', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783427', N'TH Phạm Văn Cội', N'Ấp 3', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783428', N'TH Phú Hòa Đông', N'378A  Ấp Phú Thuận', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783429', N'TH Phú Hòa Đông 2', N'Xã Phú Hòa Đông Huyện Củ Chi TP Hồ Chí Minh.', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783430', N'TH Tân Thạnh Tây', N'Ấp 2', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783431', N'TH Trung An', N'Đường Võ Thị Hồng Ấp chợ', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783432', N'TH Hòa Phú', N'Đường Bến Than Ấp 1A Xã Hòa Phú - Huyện Củ Chi -TPHCM', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783433', N'TH Bình Mỹ', N'Ấp 6B Xã Bình mỹ củ chi TPHCM', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783434', N'TH Bình Mỹ 2', N'Tỉnh Lộ 9 Ấp 4a', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783435', N'TH Tân Thạnh Đông', N'Tỉnh lộ 15 ấp 10', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783436', N'TH Tân Thạnh Đông 2', N'Ấp 4', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783437', N'TH Tân Thạnh Đông 3', N'655 Tỉnh lộ 15 Ấp 6', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783438', N'TH Tân Thông', N'Ấp Chánh xã Tân Thông Hội huyện Củ Chi', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783439', N'TH Thị Trấn 2', N'Đường Ninh Tốn Khu phố 2', 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79783499', N'TH Nguyễn Thị Lắng', NULL, 1, 3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784401', N'TH NGUYỄN AN NINH', N'Số 79 đường Lê Lợi Khu phố 4 Thị Trấn Hóc Mônhuyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784402', N'TH Thới Tam', N'4/111 đường Trần Thị Bốc ấp Nam Thới Xã Thới Tam Thôn huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784403', N'TH Tam Đông', N'152/5BĐường Thới Tam Thôn ấp Tam Đông Xã Thới Tam Thôn Huyện Hóc Môn TPHCM', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784404', N'TH TAM ĐÔNG 2', N'19/23 đường Thới Tứ 2Ấp Thới Tứ xã Thới Tam Thôn huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784405', N'TH MỸ HUỀ', N'59/5A đường Quốc lộ 22 ấp Mỹ Hòa 1 xã Trung Chánh huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784406', N'NAM KỲ KHỞI NGHĨA', N'28/1 đường Hồ Ngọc Cẩn ấp Trung Chánh 1 xã Trung Chánh huyện Hóc Môn.', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784407', N'TH MỸ HÒA', N'58/8D đường Tân Xuân 6 Ấp Mỹ Hoà 3 xã Tân Xuân huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784408', N'TH ẤP ĐÌNH', N'170 đường Lê Thị Hà Ấp Chánh 1 xã Tân Xuân huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784409', N'TH TÂN HIỆP', N'187đường Lê Lợi Ấp Tân Thới 3 xã Tân Hiệp huyện Hóc Môn Thành phố Hồ Chí Minh', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784410', N'TH Cầu Xáng', N'50 đường Liên Xã Tân Hiệp ấp Thới Tây  2 xã Tân Hiệp huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784411', N'TH TÂY BẮC LÂN', N'51/2 đường Nguyễn Thị Huê ấp Hậu Lân xã Bà Điểm huyện Hóc Môn TP.HCM', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784412', N'TH LÝ CHÍNH THẮNG 2', N'90/9A Đường Tân Thới Nhì 9 Ấp Thống Nhất 2 Xã Tân Thới Nhì Huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784413', N'TH NHỊ TÂN', N'2/51 đường Dương Công KhiẤp Tân Lập xã Tân Thới Nhì huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784414', N'TH NGÃ BA GIỒNG', N'10 Đường Phan Văn Hớn Ấp 4 xã Xuân Thới Thượng huyện Hóc Môn TP HCM.', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784415', N'TH HOÀNG HOA THÁM', N'209 đường Đặng Thúc Vịnh Ấp 7 Xã Đông Thạnh huyện Hóc Môn tphcm', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784416', N'TH THỚI THẠNH', N'363 Đường Đặng Thúc Vịnh ấp 1 xã Đông Thạnh huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784417', N'TH DƯƠNG CÔNG KHI', N'50/43 đường Lê Thị Kim Xuân Thới Sơn ấp 6 xã Xuân Thới Sơn huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784418', N'TH VÕ VĂN THẶNG', N'số 170 đường Bùi Công Trừng ấp 4 xã Nhị Bình huyện Hóc Môn Tp.HCM', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784419', N'TH BÙI VĂN NGỮ', N'1/21 đường Phan Văn Hớn ấp Tiền Lân xã Bà Điểm huyện Hóc Môn.', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784420', N'TH TRƯƠNG VĂN NGÀI', N'107 đường liên xã Tân Hiệp ấp Tân Thới 2 huyện Hóc Môn Tp.HCM', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784421', N'TH NHỊ XUÂN', N'8B đường Nguyễn Văn Bứa Ấp 5 xã Xuân Thới Sơn huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784422', N'TH Tân Xuân', N'3/6B quốc lộ 22 ấp Mỹ Hòa 4 xã Xuân Thới Đông Huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784423', N'TH XUÂN THỚI THƯỢNG', N'10 đường Phan Văn Hớn Ấp 2 Xã Xuân Thới Thượng Huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784424', N'TH Trần Văn Mười', N'70 đường Trần Văn Mười ấp Xuân Thới Đông 3 xã Xuân Thới Đông huyện Hóc Môn', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784425', N'TH TRẦN VĂN DANH', N'11A đường Đặng Thúc Vịnh Ấp 7 xã Đông Thạnh huyện Hóc Môn.', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79784426', N'NGUYỄN THỊ NUÔI', N'402 Tô Ký ấp Tam Đông 1 xã Thới Tam Thôn huyện Hóc Môn.', 1, 3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785401', N'TH Bình Hưng', N'3a Đường Số 10  Kdc Bình Hưng', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785402', N'TH Võ Văn Vân', N'Ấp 1 xã Phạm Văn Hai', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785403', N'TH Phong Phú', N'QL50 Ấp 2xã Phong Phú huyện Bình Chánh', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785404', N'TH Nguyễn Văn Trân', N'E13/414-Đa Phước Bình Chánh TPHCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785405', N'TH Qui Đức', N'A6/12 xã Qui Đức huyện Bình Chánh TpHCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785406', N'TH Hưng Long', N'Đường Đoàn Nguyễn Tuân - C1/30 ấp 3 xã Hưng Long huyện Bình Chánh', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785407', N'TH Tân Quý Tây', N'Ấp 2 xã Tân Quý Tây huyện Bình Chánh TPHCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785408', N'TH Tân Quý Tây 3', N'Ấp 2 đường Đoàn Nguyễn Tuân xã Tân Quý Tây huyện Bình Chánh.', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785409', N'TH Bình Chánh', N'c5/42 Trịnh Như Khuê Ấp 3 Bình Chánh xã Bình Chánh Huyện Bình Chánh TPHCM.', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785410', N'TH An Phú Tây', N'Ấp 2 Xã An Phú Tây', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785411', N'TH Tân Túc', N'C1/3G KP3 Thị Trấn Tân Túc Huyện Bình Chánh TP Hồ Chí Minh', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785412', N'TH Tân Kiên', N'Số 2 đường số 2 khu tái định cư ấp 2 xã Tân Kiên', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785413', N'TH Phạm Văn Hai', N'1A256 Ấp 1 đường Trần Văn Giàu', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785414', N'TH An Hạ', N'Ấp 6 xã Phạm Văn Hai huyện Bình Chánh Thành phố HỒ Chí Minh', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785415', N'TH Bình Lợi', N'B3/314 Ấp 2 xã Bình Lợi Bình Chánh Tp.HCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785416', N'TH Cầu Xáng', N'A3/33 Trần Văn Giàu Ấp 1', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785417', N'TH Lê Minh Xuân 2', N'E5/18 Lý Văn Mạnh Kênh B xã Lê Minh Xuân huyện Bình Chánh TPHCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785418', N'Tiểu học Lê Minh Xuân 3', N'Đường Lê Đình Chi ấp 3 xã Lê Minh Xuân huyện Bình Chánh', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785419', N'TH Tân Nhựt', N'A7/178c Ấp 1 Tân Nhựt', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785420', N'TH Tân Nhựt 6', N'E3/56A', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785421', N'TH Vĩnh Lộc 1', N'A2/18 ấp 1 xã Vĩnh Lộc A - Huyện Bình Chánh - TP.HCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785422', N'TH Vĩnh Lộc 2', N'C3/17a Ấp 3', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785423', N'TH Vĩnh Lộc A', N'F7/32 ẤP 6', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785424', N'Tiểu học Vĩnh Lộc B', N'42B KDC Vĩnh Lộc Ấp 1 xã Vĩnh Lộc B huyện Bình Chánh Tp.HCM.', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785427', N'TH Lại Hùng Cường', N'Ấp 2xã Vĩnh Lộc B Huyện Bình Chánh TPHCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785428', N'TH Trần Nhân Tôn', N'B15/7 ấp 2 xã Bình Chánh huyện Bình Chánh Thành phố Hồ Chí Minh', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785429', N'TH Trần Quốc Toản', N'Ấp 4 xã Vĩnh Lộc B huyện Bình Chánh TP.HCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785430', N'TH Phạm Hùng', N'Đường 6A Khu dân cư Đại Phúc ấp 5', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785431', N'TH Phong Phú 2', N'Khu Dân Cư Phong Phú 4Xã Phong Phú Huyện Bình Chánh Thành Phố Hồ Chí Minh.', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785432', N'Trường Tiểu Học An Phú Tây 2', N'đường số 5 khu dân cư An Phú Tây xã An Phú Tây Huyện Bình Chánh. TPHCM', 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785433', N'TH Tân Túc 2', NULL, 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785434', N'TH Huỳnh Văn Bánh', NULL, 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785435', N'TH Việt Mỹ', NULL, 2, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79785436', N'TH Kim Đồng', NULL, 1, 3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786402', N'TH Bùi Văn Ba', N'Số 8 đường số 11 khu dân cư Phước Kiển A Lê Văn Lương ấp 5 xã Phước Kiển huyện Nhà Bè', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786403', N'Tiểu học Lâm Văn Bền', N'373 Huỳnh Tấn Phát Khu Phố 7', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786404', N'TH Nguyễn Trực', N'1026/3 Ấp 5 Xã Phú Xuân - Huyện Nhà Bè', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786405', N'TH Nguyễn Bình', N'247 đường Nguyễn Bình Ấp 2 xã Phú Xuân huyện Nhà Bè', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786406', N'TH Trang Tấn Khương', N'Ấp 1 xã Long Thới', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786407', N'TH Dương Văn Lịch', N'774A Nguyễn Văn Tạo Ấp 1', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786408', N'TH Nguyễn Văn Tạo', N'1401 Nguyễn Văn Tạo Ấp 3 Xã Hiệp Phước huyện Nhà Bè Thành phố Hồ Chí Minh', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786409', N'TH Tạ Uyên', N'782 Lê Văn Lương Ấp 1', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786410', N'TH Lê Quang Định', N'218B Lê Văn Lương ấp 3 Phước Kiển Nhà Bè', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786411', N'Tiểu học Bùi Thanh Khiết', N'435 đường Đào Sư Tích ấp 3 xã Phước Lộc huyện Nhà Bè', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786412', N'TH Lê Lợi', N'548/17 hẽm 15 Nguyễn Bình ấp 2', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786413', N'TH Lê Văn Lương', N'Ấp 4 Nhơn Đức Nhà Bè Tp.HCM', 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79786414', N'TH Nguyễn Việt Hồng', NULL, 1, 3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787401', N'TH An Nghĩa', N'Ấp An Nghĩa Xã An Thới Đông huyện Cần Giờ. TP Hồ Chí Minh', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787402', N'TH An Thới Đông', N'Ấp An Hòa Xã An Thới Đông', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787403', N'TH Doi Lầu', N'Ấp Doi Lầu Xã An Thới Đông huyện Cần Giờ Thành Phố Hồ Chí Minh', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787404', N'TH Bình Khánh', N'Đường Rừng Sác Ấp Bình Thuận- xã Bình Khánh', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787405', N'TH Bình Mỹ', N'Đường Trần Quang Đạo ẤP Bình Mỹ Xã Bình Khánh Huyện Cần Giờ', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787406', N'TH Bình Phước', N'Ấp Bình An Xã Bình Khánh Huyện Cần Giờ.', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787407', N'TH Bình Thạnh', N'Đường Hà Quang Vóc Ấp Bình Thạnh Xã Bình Khánh Huyện Cần Giờ TP HCM', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787408', N'TH Cần Thạnh', N'Đường Duyên Hải- thị trấn Cần Thạnh', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787409', N'Tiểu học Đồng Hoà', N'Ấp Đồng Tranh- xã Đồng Hòa - huyện Cần Giờ', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787410', N'TH Hoà Hiệp', N'Ấp Hoà Hiệp- xã Long Hòa', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787411', N'TH Long Thạnh', N'Đường Duyên Hải Ấp Long Thạnh Xã Long Hoà', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787412', N'Trường Tiểu học Lý Nhơn', N'Ấp Tân Điền Lý Nhơn Huyện Cần Giờ Thành Phố Hồ Chí Minh', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787413', N'TH Tam Thôn Hiệp', N'Ấp An Lôc xã Tam Thôn hiệp', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787414', N'TH Thạnh An', N'159 Ấp Thạnh Bình', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787415', N'TH Vàm Sát', N'Đường Lý Nhơn - Ấp Lý Hòa Hiệp - xã Lý Nhơn - Cần Giờ - Thành phố Hồ Chí Minh', 1, 3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt, maphong, tenso) VALUES (N'79787416', N'TH Cần Thạnh 2', NULL, 1, 3, 24, N'SGD&DT HCM');
