INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000707', N'Phổ thông Năng khiếu thể thao Olympic', N'Đại học Thể dục thể thao TP. Hồ Chí Minh
Khu phố 6 - phường Linh Trung - Quận Thủ Đức - TP. Hồ Chí Minh', 1,4, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000774', N'TH - THCS - THPT Chu Văn An', N'Số 7 Đường Số 1 Khu Phố 1', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000791', N'Trung học cơ sở và trung học phổ thông Phùng Hưng', N'14A Đường số 1 Phường 16 Quận Gò vấp TP Hồ Chí Minh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000799', N'THCS - THPT Trần Cao Vân', N'126 Tô Hiệu', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A4', N'THCS và THPT Nam Việt', N'25 21/1-3 23/7-9 Dương Đức Hiền', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B4', N'THCS và THPT Hai Bà Trưng', N'51/4 Nguyễn Thị Nhỏ', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B9', N'Tiểu học THCS và THPT Mùa Xuân', N'92 Nguyễn Hữu Cảnh phường 22 Quận Bình Thạnh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000809', N'THCS và THPT Đăng Khoa', N'571 Cô Bắc', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000810', N'THCS và THPT Hồng Hà', N'170 Quang Trung', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000811', N'TH THCS THPT Tuệ Đức (2)', N'249/108 Tân Thới Nhất 17', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000812', N'THCS và THPT Nguyễn Bỉnh Khiêm', N'140 Lý Chính Thắng', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000813', N'Tiểu học THCS và THPT Ngô Thời Nhiệm', N'65D Hồ Bá Phấn', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000814', N'THCSTHPT An Đông', N'91 Nguyễn Chí Thanh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000815', N'THCS THPT  Ngôi Sao', N'Đường số 18 Khu dân cư An Lạc', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000816', N'THCS-THPT Phan Bội Châu', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000818', N'TH - THCS - THPT VẠN HẠNH', N'781e Lê Hồng Phong P12 Q10', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000820', N'THPT Nam Sài Gòn', N'Khu A Nam Sài Gòn', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000822', N'THCS-THPT Hồng Đức', N'Số 8Đường Hồ Đắc DiPhường Tây ThạnhQuận Tân Phú TP Hồ Chí Minh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000824', N'THCS và THPT Bắc Sơn', N'338/24 Nguyễn Văn Quá P. Đông Hưng Thuận Quận 12', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000825', N'THCS và THPT Phạm Ngũ Lão', N'69/11 Phạm Văn Chiêu P14 Gò Vấp', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000826', N'THCS và THPT Bạch Đằng', N'53/1 Phan Văn Hớn', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000828', N'TH THCS và THPT Quốc Tế', N'305 Nguyễn Trọng Tuyển Phường 10 Quận Phú Nhuận', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000829', N'THCS và THPT  Việt Thanh', N'261 Cộng Hòa', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000830', N'THCS và THPT Trí Đức', N'1333A Thoại Ngọc Hầu', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000831', N'THCS và THPT Thái Bình', N'10 Trương Hoàng Thanh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000832', N'TH-THCS-THPT Thanh Bình', N'192/12 Nguyễn Thái Bình', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000834', N'THCS và THPT Nhân Văn', N'17 Sơn Kỳ', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000835', N'THCS - THPT Nguyễn Khuyến', N'136 Cộng Hòa', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000836', N'TH THCS và THPT Trương Vĩnh Ký', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000838', N'THCS THPT Phan Châu Trinh', N'Số 12 Đường 23', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000841', N'THCS - THPT Duy Tân', N'106 Nguyễn Giản Thanh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000846', N'THCS và THPT Châu Á Thái Bình Dương', N'33 C D E Nguyễn Bỉnh Khiêm', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000848', N'Tiểu học THCS và THPT Việt Mỹ', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000849', N'THCS và THPT Đức Trí', N'39/23 Bùi Văn Ba khu phố 2', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000850', N'THCS và THPT Đinh Thiện Lý', N'Lô 01 Khu A Nam Sài Gòn', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000851', N'THCS - THPT Sao Việt', N'650q/15 Nguyễn Hữu Thọ', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000852', N'TH THCS và THPT Nam Mỹ', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000853', N'Trung học thực hành Sài Gòn', N'220 Tần Bình Trọng', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000854', N'THCS - THPT Lạc Hồng', N'2276/5 Quốc lộ 1A', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000855', N'THCS và THPT Quang Trung Nguyễn Huệ', N'223 Nguyễn Tri Phương', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000856', N'THCS và THPT Khai Minh', N'410 Tân Kỳ Tân Quý', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000857', N'THCS  VÀ THPT NGỌC VIỄN ĐÔNG', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000858', N'Tiểu học THCS và THPT Tân Phú', N'519 Kênh Tân Hóa', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000859', N'THCS - THPT Bác Ái', N'187 Gò Cẩm Đệm P.10 Q.Tân Bình TP.HCM', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000860', N'THCS và THPT Sương Nguyệt Anh', N'249 Hòa Hảo', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000861', N'THCS và THPT Diên Hồng', N'11 Thành Thái  phường 14 quận 10', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000865', N'THCS và THPT Hoa Lư', N'201 Phan Văn Hớn', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000866', N'THCS và THPT Đào Duy Anh', N'355 Nguyễn Văn Luông', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000868', N'THCS và THPT ĐINH TIÊN HOÀNG', N'85 Chế Lan Viên', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000871', N'THPT Năng Khiếu TDTT', N'43 Điện Biên Phủ', 1,4, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000872', N'THCS và THPT Việt Anh', N'269A Nguyễn Trọng Tuyển P10 Phú Nhuận', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000873', N'THCS và THPT Hoa Sen', N'26 Phan Chu Trinh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000874', N'Tiểu học THCS và THPT Vinschool', N'Tòa CC3 khu đô thị Vinhomes Central Park 720A Điện Biên Phủ', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000876', N'THCS và THPT Thạnh An', NULL, 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000888', N'Tiểu học THCS và THPT Lê Thánh Tông', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C01', N'PTDL Hermann Gmeiner', N'697 Quang Trung', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C03', N'Tiểu học THCS và THPT Việt Úc', N'594 Ba Tháng Hai - phường 14 - Quận 10 - Tp. HCM', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C04', N'THCS Song ngữ Quốc tế Horizon', N'6-6A-8 dường số 44', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C05', N'Tiểu học THCS và THPT Quốc tế Canada', N'Số 86 Đường 23', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C06', N'TiH - THCS - THPT QUỐC TẾ BẮC MỸ', N'1 Đường 5A Kdc Trung Sơn', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C07', N'Tiểu học THCS và THPT Thái Bình Dương', N'125 Bạch Đằng', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C09', N'TH THCS VÀ THPT Nguyễn Tri Phương', N'61a Đường 30', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C10', N'Tiểu học THCS và THPT Anh Quốc', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C11', N'Tiểu học THCS và THPT Emasi Nam Long', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C12', N'Tiểu học THCS và THPT Mỹ Việt', N'95 Phan Văn Hớn-Phường Tân Thới Nhất-Quận 12 - Thành Phố Hồ Chí Minh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C13', N'Tiểu học THCS và THPT Emasi Vạn Phúc', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C15', N'Tiểu học THCS và THPT Hoàng Gia', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000C19', N'Tiểu học THCS và THPT Albert Einstein', N'Khu Dân Cư 13c đại lộ Nguyễn Văn Linh xã Phong Phú huyện Bình Chánh TP Hồ Chí Minh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000F03', N'THPT Chuyên Năng khiếu TDTT Nguyễn Thị Định', N'215 Đường Hoàng Ngân', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'7900QT01', N'Tiểu học THCS và THPT Quốc tế Khai Sáng', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'7900QT02', N'Trường Quốc tế Việt Nam - Phần Lan', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'7900QT2', N'Trường Quốc tế Việt Nam - Phần Lan', NULL, 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760419', N'Tiểu học THCS  và THPT Quốc tế Á Châu', N'Số 41/3-41/4 Bis Trần Nhật Duật', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767601', N'Tiểu học THCS và THPT Hòa Bình', N'69 Trịnh Đình Thảo', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770601', N'TiH - THCS - THPT Tây Úc', N'157 Lý Chính Thắng', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760501', N'THCS Chu Văn An', N'115 Cống Quỳnh', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760502', N'THCS Trần Văn Ơn', N'161B Nguyễn Văn Thủ', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760503', N'THCS Minh Đức', N'75 Nguyễn Thái Học', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760504', N'THCS Nguyễn Du Q1', N'139 Nguyễn Du', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760505', N'THCS Văn Lang', N'51 Trần Quý Khách', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760506', N'THCS Võ Trường Toản', N'11 Nguyễn Bỉnh Khiêm', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760507', N'THCS Đức Trí', N'273 Nguyễn Trãi', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760508', N'THCS Đồng Khởi', N'11 Phan Văn Trường', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79760509', N'THCS Huỳnh Khương Ninh', N'61 Huỳnh Khương Ninh', 1,3, 1, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761501', N'THCS An Phú Đông', N'2688/1A Khu Phố 1', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761502', N'THCS Nguyễn An Ninh', N'2384/36 Kp5', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761503', N'THCS Phan Bội Châu', N'Đường ĐHT 30 Khu phố 4 Phường Đông Hưng Thuận Q12 TP.HCM', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761504', N'THCS Lương Thế Vinh', N'301/34 Kp3', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761505', N'THCS Nguyễn Ảnh Thủ', N'224 Phan Văn Hớn Khu Phố 6 P.Tân Thới Nhất Q12TPHCM', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761506', N'THCS Nguyễn Vĩnh Nghiệp', N'51/5B Kp2', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761507', N'THCS Nguyễn Hiền', N'Khu Phố 3a', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761508', N'THCS Trần Quang Khải', N'641 Kp8', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761509', N'THCS Nguyễn Huệ', N'2K Nguyễn Thị Đặng Khu phố 6', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761510', N'THCS Trần Hưng Đạo', N'Khu Phố 1', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761511', N'THCS Nguyễn Trung Trực', N'364 Đường TA28  Kp 5 phường Thới An quận 12', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761512', N'THCS Nguyễn Chí Thanh', N'Khu phố 3', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761513', N'THCS Hà Huy Tập', N'Khu phố 5 phường Đông Hưng Thuận Q12 TP.HCM', 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79761514', N'THCS Trần Phú', NULL, 1,3, 12, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762501', N'THCS Lê Quý Đôn', N'234 Võ Văn Ngân', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762502', N'THCS Trương Văn Ngư', N'49 Võ Văn Ngân KP2', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762503', N'THCS Ngô Chí Quốc', N'Số 23 Đường 27 Kp9', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762504', N'THCS Hiệp Bình', N'số 4 đường số 4 Kp6', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762505', N'THCS Thái Văn Lung', N'35 Phú Châu', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762506', N'THCS Tam Bình', N'Số 2 Đường 10 Kp4', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762507', N'THCS Xuân Trường', N'47 QL1K Kp2', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762508', N'THCS Linh Trung', N'số 5 Kp2', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762509', N'THCS Linh Đông', N'Kp4', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762510', N'THCS Bình Chiểu', N'Số 2 Kp3 đường Bình Chiểu', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762511', N'THCS Bình Thọ', N'39 Thống Nhất', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762512', N'THCS Lê Văn Việt', N'15 Nguyễn  Bá Luật kp2 p.Bình Thọ. q.Thủ Đức TP.HCM', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762514', N'THCS Nguyễn Văn Bá', N'99/21 Đường 11 Kp4', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762515', N'THCS Trường Thọ', N'71/25 Đường 8 Khu Phố 2 Phường Trường Thọ Quận Thủ Đức', 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79762516', N'THCS Dương Văn Thì', NULL, 1,3, 13, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763501', N'THCS Phước Bình', N'02 Đường 22 Phước Bình', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763502', N'THCS Hưng Bình', N'819 Nguyễn Xiển KP Long Hòa P. Long Thạnh Mỹ Q.9', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763503', N'THCS Hoa Lư', N'Đường Quang Trung', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763504', N'THCS Trần Quốc Toản', N'381 đường Lê Văn Việt', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763505', N'THCS Long Trường', N'Nguyễn Duy TrinhKhu phố Ông Nhiêu', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763506', N'THCS Long Phước', N'18 Đường 6 Kp Long Thuận', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763507', N'THCS Đặng Tấn Tài', N'Đường 128 KP4 Phước Long A', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763508', N'THCS Phú Hữu', N'Khu phố 1 Phường Phú Hữu Q9 Tp.HCM', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763509', N'THCS Tân Phú', N'119 Nam Cao', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763510', N'THCS Trường Thạnh', N'3/1 đường 3 KP Phước Hiệp', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763511', N'THCS Long Bình', N'1080 Nguyễn Xiển KP.Bến Đò P. Long Bình Quận 9', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763512', N'THCS Tăng Nhơn Phú B', N'Dương Đình Hội Khu phố 3 Phường Tăng Nhơn Phú B Quận 9 HCM', 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79763513', N'THCS Hiệp Phú', NULL, 1,3, 9, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764501', N'THCS Nguyễn Văn Trỗi', N'112/24 Nguyễn Thái Sơn', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764502', N'THCS Nguyễn Du', N'119 Thống Nhất', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764503', N'THCS Gò Vấp', N'01 Nguyễn Du', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764504', N'THCS Quang Trung', N'387 Quang Trung Phường 10 Quận Gò Vấp TPHCM', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764505', N'THCS Phạm Văn Chiêu', N'Số 4 Phạm Văn Chiêu', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764507', N'THCS Phan Tây Hồ', N'18B/27 Thống Nhất', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764508', N'THCS An Nhơn', N'350/54/51 Lê Đức Thọ', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764509', N'THCS Nguyễn Văn Nghi', N'111 Lương Ngọc Quyến', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764510', N'THCS Trường Sơn', N'43 Nguyễn Văn Bảo', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764511', N'THCS Thông Tây Hội', N'01 Quang Trung', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764512', N'THCS Lý Tự Trọng', N'578 Lê Đức Thọ', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764513', N'THCS Nguyễn Trãi', N'1370 Lê Đức Thọ', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764514', N'THCS Tân Sơn', N'162/27 Nguyễn Duy Cung', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764515', N'THCS Huỳnh Văn Nghệ', N'237/65 Phạm Văn Chiêu', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79764516', N'THCS Phan Văn Trị', N'468/2/2 Phan Văn Trị Phường 7 Gò Vấp', 1,3, 15, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765501', N'THCS Lam Sơn', N'280 Bùi Hữu Nghĩa', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765502', N'THCS Hà Huy Tập', N'Số 7 Phan Đăng Lưu', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765503', N'THCS Nguyễn Văn Bé', N'206 Nguyễn Văn Đậu', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765504', N'THCS Rạng Đông', N'17 Ngô Đức Kế p.12 QBình Thạnh', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765505', N'THCS Bình Lợi Trung', N'179 Đường Trục', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765506', N'THCS Lê Văn Tám', N'107F Chu Văn An', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765507', N'THCS Phú Mỹ', N'120B Ngô Tất Tố', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765508', N'THCS Cửu Long', N'102 Ngô Tất Tố', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765509', N'THCS Đống Đa', N'217 Đường D2 Phường 25 Quận Bình Thạnh', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765510', N'THCS Thanh Đa', N'Cạnh Lô L Cư Xá Thanh Đa', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765511', N'THCS  Trương Công Định', N'131 Đinh Tiên Hoàng', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765512', N'THCS Yên Thế', N'399 Lê Quang Định', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765513', N'THCS Điện Biên', N'200 Điện Biên Phủ', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765514', N'THCS Cù Chính Lan', N'17/49 Thanh Đa', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79765515', N'THCS Bình Quới Tây', N'376A Bình Quới', 1,3, 16, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766501', N'THCS Ngô Sĩ Liên', N'12 Phạm Văn Hai', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766502', N'THCS Trần Văn Đang', N'27 Nghĩa Hoà', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766503', N'THCS Nguyễn Gia Thiều', N'272 Lý Thường Kiệt', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766504', N'THCS Quang Trung', N'14-16 Tân Lập', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766505', N'THCS Lý Thường Kiệt', N'104 Thiên Phước', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766506', N'THCS Võ Văn Tần', N'261 Võ Thành Trang', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766507', N'THCS Hoàng Hoa Thám', N'135 Hoàng Hoa Thám', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766508', N'THCS Âu Lạc', N'46 Hoàng Việt phường 4 quận Tân Bình', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766509', N'THCS Tân Bình', N'873 Cách Mạng Tháng Tám', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766510', N'THCS Phạm Ngọc Thạch', N'17-19 Âu Cơ', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766511', N'THCS Ngô Quyền', N'97 Trường Chinh', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766512', N'THCS Trường Chinh', N'162t Trường Chinh', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79766513', N'THCS Trần Văn Quang', N'Ni sư Huỳnh Liên Phường 10 Quận Tân Bình', 1,3, 17, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767418', N'THCS Hồng Ngọc', N'58/4 Lũy Bán Bích', 2,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767501', N'THCS Đặng Trần Côn', N'15/29 Cầu Xéo', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767502', N'THCS Lê Lợi', N'47/22a Đường S11', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767503', N'THCS Võ Thành Trang', N'218 Tân Quý', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767504', N'THCS Đồng Khởi', N'20 Thạch Lam', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767505', N'THCS Hùng Vương', N'20f Lương Minh Nguyệt', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767506', N'THCS Lê Anh Xuân', N'211/53 Vườn Lài', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767507', N'THCS Phan Bội Châu', N'35 Độc Lập', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767508', N'THCS Tân Thới Hòa', N'149/15 Lý Thánh Tông phường Tân Thới Hòa quận Tân Phú TP.HCM', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767509', N'THCS Thoại Ngọc Hầu', N'24 Huỳnh Văn Chính', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767510', N'THCS Trần Quang Khải', N'94/3 Nguyễn Thế Truyện', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767511', N'THCS Nguyễn Huệ', N'289 Thành Công', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767512', N'THCS Hoàng Diệu', NULL, 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79767513', N'THCS Tôn Thất Tùng', N'3 đường D2 phường Sơn Kỳ quận Tân Phú TP HCM', 1,3, 18, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79768501', N'THCS Cầu Kiệu', N'244 Phan Đình Phùng', 1,3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79768502', N'TRƯỜNG THCS Độc Lập', N'94 Thích Quảng Đức', 1,3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79768503', N'THCS Ngô Tất Tố', N'17 Đặng Văn Ngữ', 1,3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79768504', N'THCS Châu Văn Liêm', N'93 Phan Đăng Lưu', 1,3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79768506', N'THCS Đào Duy Anh', N'14 Lê Quí Đôn', 1,3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79768507', N'THCS Trần Huy Liệu', N'94 Nguyễn Đình Chiểu', 1,3, 19, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769411', N'TH - THCS Tuệ Đức', N'1/5 Bis Lương Định Của', 2,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769501', N'THCS An Phú', N'589C Khu phố 4', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769502', N'THCS Giồng Ông Tố', N'256B Nguyễn Duy Trinh', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769503', N'THCS Nguyễn Văn Trỗi', N'571 Nguyễn Duy Trinh', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769504', N'THCS Thạnh Mỹ Lợi', N'42 đường 5 Khu phố 2', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769506', N'THCS Lương Định Của', N'Số 2 Đường Lê Hiến Mai', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769507', N'THCS Bình An', N'25 Đường 34 Kp2', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769508', N'THCS Nguyễn Thị Định', N'Số 2 Đường 7 Kp2', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769509', N'THCS Trần Quốc Toản', N'218 Vũ Tông Phan Phường An Phú Quận 2', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79769510', N'THCS Cát Lái', N'Số 15 Đường 69 KP3 Phường Cát Lái Quận 2', 1,3, 2, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770501', N'THCS Bàn Cờ', N'16 Đường Số 3 C/x Đô Thành', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770502', N'THCS Colette', N'10 Hồ Xuân Hương Phuờng 6 Quận 3', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770503', N'THCS Đoàn Thị Điểm', N'413/86 Lê Văn Sỹ', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770504', N'THCS Hai Bà Trưng', N'295 Hai Bà Trưng', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770505', N'THCS Lê lợi', N'282 Võ Thị Sáu', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770506', N'THCS Lê Quý Đôn', N'9B Võ Văn Tần', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770507', N'THCS Lương Thế Vinh', N'474 CMT8', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770508', N'THCS Thăng Long', N'482-484 Nguyễn Thị Minh Khai', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770509', N'THCS Bạch Đằng', N'386/42 Lê Văn Sỹ', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770510', N'THCS Kiến Thiết', N'223/4 Nguyễn Đình Chiểu', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79770511', N'THCS Phan Sào Nam', N'657 Điện Biên Phủ', 1,3, 3, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79771501', N'THCS Hoàng Văn Thụ', N'322 Nguyễn Tri Phương', 1,3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79771502', N'THCS Nguyễn Tri Phương', N'26 Nguyễn Lâm', 1,3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79771503', N'THCS Nguyễn Văn Tố', N'332 - 334 Tô Hiến Thành', 1,3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79771504', N'THCS Lạc Hồng', N'436/4 Ba Tháng Hai', 1,3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79771505', N'THCS Trần Phú', N'82 Cửu Long', 1,3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79771507', N'THCS Cách Mạng Tháng Tám', N'289 Cách Mạng Tháng 8', 1,3, 10, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772501', N'THCS Nguyễn Văn Phú', N'161B/112 Lạc Long Quân', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772502', N'THCS Lê Quý Đôn', N'343D Lạc Long Quân', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772503', N'THCS Nguyễn Huệ', N'429/9 Lạc Long Quân', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772504', N'THCS Nguyễn Minh Hoàng', N'185/2 Lý Thường Kiệt', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772505', N'THCS Chu Văn An', N'01 Dương Đình Nghệ', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772506', N'THCS Lê Anh Xuân', N'40 đường 762 Hồng Bàng', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772507', N'THCS Phú Thọ', N'1122 đường 3/2', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772508', N'THCS Lữ Gia', N'52/1A cư xá Lữ Gia', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772509', N'THCS Hậu Giang', N'8 Lò Siêu', 1,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79772511', N'THCS Việt Mỹ', N'252 Lạc Long Quân', 2,3, 11, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79773501', N'THCS Nguyễn Huệ', N'42 Nguyễn Khoái', 1,3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79773502', N'THCS Quang Trung', N'209 Đường 14', 1,3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79773503', N'THCS Tăng Bạt Hổ', N'92 B/20 Bis Tôn Thất Thuyết', 1,3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79773504', N'THCS Vân Đồn', N'243 Hoàng Diệu Phường 8 Quận 4', 1,3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79773506', N'THCS Chi Lăng', N'129/63A Nguyễn Hữu Hào', 1,3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79773507', N'THCS Khánh Hội', N'A75 Nguyễn Thần Hiến', 1,3, 4, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774501', N'THCS Ba Đình', N'129 Phan Văn Trị', 1,3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774502', N'Trung học cơ sở Kim Đồng', N'503 Phan Văn Trị', 1,3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774503', N'THCS Hồng Bàng', N'132 Hồng Bàng', 1,3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774504', N'THCS Trần Bội Cơ', N'266 Hải Thượng Lãn Ông', 1,3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774505', N'THCS Lý Phong', N'83 Nguyễn Duy Dương', 1,3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774506', N'THCS Mạch Kiếm Hùng', N'712 Nguyễn Trãi', 1,3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774601', N'THCS Văn Lang', N'02-04 Tân Thành', 2,3, 5, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775421', N'TH - THCS QT Mỹ Úc(TH)', N'62_62A Minh Phung', 2,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775501', N'THCS Nguyễn Đức Cảnh', N'242-minh Phụng', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775502', N'THCS Phú Định', N'94bis Lý Chiêu Hoàng', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775503', N'THCS Hậu Giang', N'176/1A Hậu Giang', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775504', N'THCS Phạm Đình Hổ', N'270 Gia Phú', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775505', N'THCS Đoàn Kết', N'183A Tân Hoà Đông', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775506', N'THCS Nguyễn Văn Luông', N'241/159 Nguyễn Văn Luông Phường 11 Quận 6', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775507', N'Trường THCS Lam Sơn', N'805a Hậu Giang', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775508', N'THCS Bình Tây', N'36A Bình Tây', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775509', N'THCS Văn Thân', N'118B Văn Thân', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79775510', N'THCS Hoàng Lê Kha', N'383-391 Bến Phú Lâm', 1,3, 6, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776501', N'THCS Dương Bá Trạc', N'134 Dương Bá Trạc', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776502', N'THCS Khánh Bình', N'314B Âu Dương Lân Phường 3 Quận 8', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776503', N'THCS Chánh Hưng', N'995 Phạm Thế Hiển', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776504', N'THCS Sương Nguyệt Anh', N'53 Bùi Minh Trực', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776505', N'THCS Phan Đăng Lưu', N'104 Bis Bùi Minh Trực', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776506', N'THCS Trần Danh Ninh', N'121 Ba Đình', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776507', N'THCS Tùng Thiện Vương', N'381 Tùng thiện Vương P12 Q8 TP. Hồ Chí Minh', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776508', N'THCS Lê Lai', N'236 Bình Đông P.15', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776509', N'THCS Bình An', N'2673 Phạm Thế Hiển', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776510', N'THCS Bình Đông', N'58 Bến Phú Định', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776511', N'THCS Lý Thánh Tông', N'481 Ba Đình', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79776512', N'THCS Phú Lợi', N'số 56 đường Trịnh Quang Nghị phường 7 Quận 8 Thành phố Hồ Chí Minh', 1,3, 8, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777501', N'THCSCL An Lạc', N'4b Phùng Tá Chu  KP7 phường  An Lạc A Quận Bình Tân thành phố Hồ Chí Minh.', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777502', N'THCSCL Hồ Văn Long', N'52 Hồ Văn Long Kp4', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777503', N'THCSCL Bình Hưng Hòa', N'10/47 quốc lộ 1A Kp3', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777504', N'THCS Bình Trị Đông', N'B15/22c Hương Lộ 2p Bình Trị Đôngq Bình TânHCM', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777505', N'THCSCL Bình Tân', N'173/171 Đường An Dương Vương KP4P.An LạcTPHCM', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777506', N'THCSCL Lê Tấn Bê', N'Đường Số 2d Khu Phố 3phường An Lạc quận Bình Tân Tp.HCM', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777507', N'THCSCL Tân Tạo', N'68 Hồ Văn Long KP4', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777508', N'THCS Bình Trị Đông A', N'160A Mã Lò Khu phố 2 Phường Bình Trị Đông A Quận Bình Tân TP HCM', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777509', N'THCSCL Lý Thường Kiệt', N'33 Trương Phước Phan', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777510', N'THCSCL Trần Quốc Toản', N'76 Kênh Nước Đen KP5 Phường Bình Hưng Hòa A Q. Bình Tân TP.HCM', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777511', N'THCSCL Huỳnh Văn Nghệ', N'89đường số 3 khu phố 4', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777512', N'THCSCL Nguyễn Trãi', N'140 đường số 18', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777513', N'THCSCL Tân Tạo A', N'4449/8 Đường Nguyễn Cửu Phú Phường Tân Tạo A Quận Bình Tân Tp. Hồ Chí Minh', 1,3, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79777514', N'TH THCS và THPT Trí Tuệ Việt', N'79 đường số 3 KDC Vĩnh Lộc Bình Hưng Hòa B.', 2,6, 20, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79778501', N'THCS Trần Quốc Tuấn', N'16/1 khu phố 1 Bế Văn Cấm', 1,3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79778502', N'THCS Huỳnh Tấn Phát', N'488 Huỳnh Tấn Phát', 1,3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79778503', N'THCS Nguyễn Hữu Thọ', N'62 Lâm Văn Bền Kp4 Phường Tân KiểngQuận 7TP Hồ Chí Minh', 1,3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79778504', N'THCS Nguyễn Hiền', N'66 đường 1 Kp3', 1,3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79778505', N'THCS Hoàng Quốc Việt', N'D29 đường số 3 KDC Vạn Phát Hưng', 1,3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79778506', N'THCS Nguyễn Thị Thập', N'411/3 Nguyễn Thị Thập', 1,3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79778507', N'THCS Phạm Hữu Lầu', N'Khu Tái định cư Phú Mỹ', 1,3, 7, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783501', N'THCS Tân Phú Trung', N'Số 4 Đường 77 ấp Đình', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783502', N'THCS Tân Thông Hội', N'Đường 28 Ấp Hậu', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783503', N'THCS Tân Tiến', N'Số 41 đường 27  Ấp Tân Tiến', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783504', N'THCS Thị Trấn', N'629 QL22 KP5 Thị Trấn Củ Chi Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783505', N'THCS Thị Trấn 2', N'Lê Vĩnh Huy Khu phố 7', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783506', N'THCS Phước Vĩnh An', N'Ấp 5', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783507', N'THCS Phước Hiệp', N'Ấp Cây trôm Xã Phước Hiệp Huyện Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783508', N'THCS Phước Thạnh', N'Tỉnh lộ 7 Ấp Phước An xã Phước Thạnh huyện Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783509', N'THCS Nguyễn Văn Xơ', N'Ấp Bình Thượng 1 Thái Mỹ Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783510', N'THCS Trung Lập Hạ', N'Ấp Xóm Mới Xã Trung Lập Hạ Huyện Củ Chi TP.HCM', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783511', N'THCS Trung Lập', N'Ấp Trung Bình', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783512', N'THCS An Nhơn Tây', N'Ấp Xóm Trại', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783513', N'THCS An Phú', N'Ấp Phú Bình Xã An Phú Huyện Củ Chi Tp. HCM', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783514', N'THCS Nhuận Đức', N'Ấp Ngã Tư xã Nhuận Đức huyện Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783515', N'THCS Phạm Văn Cội', N'Số 317 Đường Bùi Thị Điệt Ấp 3', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783516', N'THCS Phú Hòa Đông', N'Số 35 Nguyễn Thị Nê Ấp Phú Hòa', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783518', N'THCS Tân Thạnh Đông', N'Ấp 7', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783519', N'THCS Bình Hòa', N'Ấp 4B', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783520', N'THCS Phú Mỹ Hưng', N'Số 16đường Phú ThuậnẤp Phú Lợi xã Phú Mỹ Hưng huyện Củ Chi TPHCM', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783521', N'THCS Hòa Phú', N'Số 1650 Tỉnh lộ 8 Ấp 1', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783522', N'THCS Tân An Hội', N'Ấp Mũi Lớn 1 Huyện Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783523', N'THCS Tân Thạnh Tây', N'Ấp 2 - Xã Tân Thạnh Tây - Huyện Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783524', N'THCS Trung An', N'Ấp An Bình', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79783600', N'TH-THCS Tân Trung', N'1310 Tỉnh Lộ 8 xã Tân Thạnh Đông Huyện Củ Chi', 1,3, 14, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784501', N'THCS Nguyễn An Khương', N'66/6 Đường Lê Thị Hồng GấmTổ 32 Khu Phố 3 Thị Trấn Hóc Môn Huyện Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784502', N'THCS THỊ TRẤN', N'23 Đường Lê Thị Hà KP8 Thị Trấn Hóc Môn Huyện Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784503', N'THCS TAM ĐÔNG 1', N'636 đường Trịnh Thị Miếng ấp Trung Đông 1 xã Thới Tam Thôn huyện Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784504', N'THCS LÝ CHÍNH THẮNG 1', N'5/5 đường Nguyễn Thị Nuôi ấp Dân Thắng 2 xã Tân Thới Nhì', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784505', N'THCS TRUNG MỸ TÂY 1', N'số 3A đường Nguyễn Ảnh Thủ ấp Mỹ Huề xã Trung Chánh huyện Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784506', N'THCS ĐÔNG THẠNH', N'Số 18 Đường Nguyễn Thị Điệp ấp 1 Đông Thạnh Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784507', N'THCS NGUYỄN HỒNG ĐÀO', N'228/2D đường Nguyễn Văn Bứa Ấp 6 xã Xuân Thới Sơn huyện Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784508', N'THCS ĐẶNG CÔNG BỈNH', N'Đường Bùi Công Trừng Ấp 3 Xã Nhị Bình Huyện Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784509', N'THCS ĐỖ VĂN DẬY', N'8 đường Huỳnh Thị Mài ấp Thới Tây 1xã Tân Hiệphuyện Hóc Môn thành phố Hồ Chí Minh', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784510', N'THCS PHAN CÔNG HỚN', N'18/6 đường Nguyễn Ảnh Thủ Ấp Trung Lân xã Bà Điểm Huyện Hóc Môn.', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784511', N'THCS TÂN XUÂN', N'01 Quốc lộ 22 Ấp Tân Tiến xã Xuân Thới Đông Huyện Hóc Môn.', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784512', N'THCS Xuân Thới Thượng', N'số 35 đường Phan Văn Hớn Ấp 4 xã Xuân Thới Thượng huyện Hóc Môn', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784513', N'THCS TÔ KÝ', N'Số 12 đường Tô Ký 12 Ấp Chánh 1 xã Tân Xuân huyện Hóc Môn TP HCM', 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79784514', N'THCS NGUYỄN VĂN BỨA', NULL, 1,3, 21, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785501', N'THCS Nguyễn Thái Bình', N'Số 9 A Đường Số 2 KDC Bình Hưng xã Bình Hưng huyện Bình Chánh Tp. HCM', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785502', N'THCS Phong Phú', N'Đường N18 KDC PHONG PHÚ 4
ẤP 3 XÃ PHONG PHÚ HUYỆN BÌNH CHÁNH', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785503', N'THCS Qui Đức', N'B10/21 Đoàn Nguyễn Tuấn xã Qui Đức Huyện Bình Chánh Thành phố Hồ Chí Minh', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785504', N'THCS Hưng Long', N'Ấp 3 Hưng Long', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785505', N'THCS Tân Quý Tây', N'16/18C ấp 4 xâ Tân Quý Tây huyện Bình Chánh Tp. Hồ Chí Minh', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785506', N'THCS Nguyễn Văn Linh', N'KDC An Phú Tây Ấp 2 xã An Phú Tây huyện Bình Chánh TpHCM', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785507', N'THCS Bình Chánh', N'B15/8 Quốc lộ 1Aấp 2', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785508', N'THCS Tân Túc', N'C1/3 Bùi Thanh KhiếtKhu phố 3 Thị Trấn Tuân Túc Huyện Bình Chánh Tp.HCM', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785509', N'THCS Tân Kiên', N'D9/13D Đường Dương Đình Cúc Ấp 4 Xã Tân Kiên Huyện Bình Chánh Tp. Hồ Chí Minh', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785510', N'THCS Phạm Văn Hai', N'3a28 Tỉnh Lộ 10 Ấp 3', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785511', N'THCS Gò Xoài', N'B2/317A Ấp 2 xã Bình Lợi Huyện Bình Chánh Tphcm', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785512', N'THCS Lê Minh Xuân', N'G8/1 Ấp 7 Lê Minh Xuân Huyện BÌnh Chánh TP.HCM', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785514', N'THCS Đồng Đen', N'F7/33 Ấp 6 Đường Quách Điêu Vĩnh Lộc A Bình Chánh TP HCM', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785515', N'THCS Vĩnh Lộc A', N'F7/31 Ấp 6 xã Vĩnh Lộc A huyện Bình Chánh Thành phố Hồ Chí Minh.', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785516', N'THCS Vĩnh Lộc B', N'F6/40 Ấp 6 A đường Lại Hùng Cường Xã Vĩnh Lộc B Huyện Bình Chánh TPHCM', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785517', N'THCS Đa Phước', N'A3/99 Quốc lộ 50 xã Đa Phước Huyện Bình chánh TPHCM', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785518', N'THCS Tân Nhựt', N'E10/207B Ấp 6 Tân Nhựt', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785519', N'THCS Võ Văn Vân', N'Khu dân cư Vĩnh Lộc B Ấp 1 xã Vĩnh Lộc B huyện Bình Chánh Tp.Hồ Chí Minh', 1,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79785601', N'TiH - THCS Thế Giới Trẻ Em(TH)', N'Số 29 đường số 3 KDC Trung Sơn', 2,3, 22, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786501', N'THCS Nguyễn Bỉnh Khiêm', N'421 Huỳnh Tấn Phát KP7 TTNB', 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786502', N'THCS Lê Văn Hưu', N'2596/20A Huỳnh Tấn Phát Xã Phú Xuân Huyện Nhà Bè TPHCM', 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786503', N'THCS Hiệp Phước', N'1154 Nguyễn Văn Tạo Ấp 3', 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786504', N'THCS Nguyễn Văn Quỳ', N'146A Lê Văn Lương Ấp 1', 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786505', N'THCS Hai Bà Trưng', N'Ấp 2 xã  Nhơn Đức', 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786506', N'THCS Phước Lộc', N'423/2 Đào Sư Tích Ấp 3 Xã Phước Lộc', 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786507', N'THCS Lê Thành Công', N'63 đường Đào Sư Tích Ấp 3 xã Phước Kiển huyện Nhà Bè TP.HCM', 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786508', N'THCS Nguyễn Thị Hương', NULL, 1,3, 23, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79787501', N'THCS An Thới Đông', N'Đường An Thới Đông-Ấp An Đông- xã An Thới Đông', 1,3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79787502', N'TRƯỜNG THCS LONG HÒA', N'Đường Duyên HảiẤp Long ThạnhXã Long Hòa Huyện Cần Giờ Tp.Hồ Chí Minh', 1,3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79787503', N'THCS Lý Nhơn', N'Ấp Lý Thái Bửu - Xã Lý Nhơn - Huyện Cần Giờ - TP .Hồ Chí MInh', 1,3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79787504', N'THCS Tam Thôn Hiệp', N'Ấp An Lộc-Xã Tam Thôn Hiệp-Huyện Cần Giờ-TP.Hồ Chí Minh.', 1,3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79787506', N'THCS Bình Khánh', N'Đường Rừng SátẤp Bình An Xã Bình Khánh', 1,3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79787507', N'THCS Cần Thạnh', N'Đường Lương Văn Nho- Khu phố Giồng Ao-Thị Trấn Cần Thạnh-Huyện Cần giờ-TPHCM', 1,3, 24, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79787508', N'THCS Doi Lầu', N'Ấp Lý Hòa Hiệp xã Lý Nhơn Huyện Cần Giờ Tp Hồ Chí Minh.', 1,3, 24, N'SGD&DT HCM');
