INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000701', N'THPT Bùi Thị Xuân', N'73 - 75 Bùi Thị Xuân', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000702', N'THPT Trưng Vương', N'3 Nguyễn Bỉnh Khiêm', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000703', N'THPT Giồng Ông Tố', N'200/10 Nguyễn Thị Định', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000704', N'THPT Nguyễn Thị Minh Khai', N'275 Điện Biên Phủ', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000705', N'THPT Lê Quý Đôn', N'110 Nguyễn Thị Minh Khai Phường 6 Quận 3 TP.Hồ Chí Minh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000706', N'THPT Nguyễn Trãi', N'364 Nguyễn Tất Thành', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000708', N'THPT Hùng Vương', N'124 Hùng Vương', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000709', N'THPT Mạc Đĩnh Chi', N'04 Tân Hòa Đông', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000710', N'THPT Bình Phú', N'102 Đường Trần Văn Kiểu Phường 1  Quận 6 TPHCM', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000711', N'THPT Lê Thánh Tôn', N'124 đường 17', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000712', N'THPT Lương Văn Can', N'173 Phạm Hùng', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000713', N'THPT Ngô Gia Tự', N'360E Bến Bình Đông', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000714', N'THPT Tạ Quang Bửu', N'909 Tạ Quang Bửu', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000715', N'THPT Nguyễn Huệ', N'Đường Nguyễn Văn Tăng Kp Châu Phúc Cẩm P.LTM Q9', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000716', N'THPT Nguyễn Khuyến', N'50 Thành Thái', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000717', N'THPT Nguyễn Du', N'XX-1 Đồng Nai', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000718', N'THPT Nguyễn Hiền', N'3 Dương Đình Nghệ-P8-Q11', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000719', N'THPT Võ Trường Toản', N'482 Đường Nguyễn Thị Đặng - Khu Phố 1', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000720', N'THPT Thanh Đa', N'186 Nguyễn Xí phường 26 quận Bình Thạnh TP.HCM', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000721', N'THPT Võ Thị Sáu', N'95 Đinh Tiên Hoàng', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000722', N'THPT Gia Định', N'195/29 Xô Viết Nghệ Tĩnh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000723', N'THPT Phan Đăng Lưu', N'27 Nguyễn Văn Đậu', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000724', N'THPT Gò Vấp', N'90A Nguyễn Thái Sơn', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000725', N'THPT Nguyễn Công Trứ', N'97 Quang Trung Phường 8 Quận Gò Vấp TP.HCM', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000726', N'THPT Phú Nhuận', N'Số 5 Hoàng Minh Giám', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000727', N'THPT Tân Bình', N'19 Hoa Bằng', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000728', N'THPT Nguyễn Chí Thanh', N'1A Nguyễn Hiến Lê', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000729', N'THPT Trần Phú', N'18 Lê Thúc Hoạch', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000730', N'THPT Nguyễn Thượng Hiền', N'544 Cách Mạng Tháng 8', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000731', N'THPT Thủ Đức', N'166/24 Đặng Văn Bi', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000732', N'THPT Nguyễn Hữu Huân', N'11 Đoàn Kết', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000733', N'THPT Tam Phú', N'31 Phú Châu Kp5', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000734', N'THPT Củ Chi', N'Tỉnh lộ 8 Khu phố 1', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000735', N'THPT Quang Trung', N'Ấp Phước An', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000736', N'THPT An Nhơn Tây', N'227Đường Tỉnh lộ 7 Ấp Chợ Cũ Xã An Nhơn Tây Huyện Củ Chi TP.HCM', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000737', N'THPT Trung Phú', N'1318 tỉnh lộ 8 Ấp 12', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000738', N'THPT Trung Lập', N'91/3 Trung Lập Ấp Trung Bình.', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000739', N'THPT Nguyễn Hữu Cầu', N'Tô Ký Ấp Mỹ Huề Xã Trung Chánh Huyện Hóc Môn TP. HCM.', 1,5, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000740', N'THPT Lý Thường Kiệt', N'Đường Nam Thới 2 Ấp Nam Thới Xã Thới Tam Thôn', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000741', N'THPT Bình Chánh', N'D17/1D Huỳnh Văn Trí', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000742', N'THPT Ten Lơ Man', N'8 Trần Hưng Đạo Phường Phạm Ngũ Lão Quận 1 Tp.Hồ Chí Minh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000743', N'THPT Marie Curie', N'159 Nam Kỳ Khởi Nghĩa', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000744', N'THPT Trần Khai Nguyên', N'225 Nguyễn Tri Phương', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000745', N'THPT Nguyễn An Ninh', N'93 Trần Nhân Tôn', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000746', N'THPT Nam Kỳ Khởi Nghĩa', N'269/8 Nguyễn Thị Nhỏ', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000747', N'THPT Nguyễn Thái Bình', N'913-915 Lý Thường Kiệt', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000748', N'THPT Nguyễn Trung Trực', N'9/168 Lê Đức Thọ', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000749', N'THPT Hàn Thuyên', N'37 Đặng Văn Ngữ', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000750', N'THPT Hoàng Hoa Thám', N'6 Hoàng Hoa Thám', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000751', N'THPT Thăng Long', N'114-116 Hải Thượng Lãn Ông', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000752', N'THPT Phước Long', N'Dương Đình Hội Khu phố 6 - Phường Phước Long B - Q.9', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000753', N'THPT Bà Điểm', N'Số7 Nguyễn Thị Sóc Ấp Bắc Lânxã Bà Điểm Huyện Hóc Môn', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000754', N'THPT Tân Phong', N'19F Nguyễn Văn Linh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000755', N'THPT Trường Chinh', N'1 DN11 Khu phố 4', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000756', N'THPT Phú Hòa', N'Số 25 đường Huỳnh Thị Bẵng Ấp Phú Lợi', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000757', N'THPT Tân Thông Hội', N'Ấp Bàu Sim', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000758', N'THPT Tây Thạnh', N'27 Đường C2', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000759', N'THPT Long Trường', N'309 Võ Văn Hát Kp Phước Hiệp phường Long Trường Quận 9 Tp. Hồ Chí Minh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000760', N'THPT Nguyễn Văn Cừ', N'100A ấp 6 xã Xuân Thới Thương Huyện Hóc Môn', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000761', N'THPT Nguyễn Hữu Tiến', N'9A Ấp 7', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000762', N'THPT Bình Khánh', N'Ấp Bình An', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000763', N'THPT Cần Thạnh', N'346 Đường Duyên Hải - Khu Phố Miễu Ba - Thị trấn Cần Thạnh - huyện Cần Giờ', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000764', N'THPT Trần Hưng Đạo', N'88/955E Lê Đức Thọ', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000765', N'THPT Hiệp Bình', N'Số 63 đường Hiệp Bình khu phố 6', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000768', N'THPT Trần Quang Khải', N'343D Lạc Long Quân', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000769', N'THPT Vĩnh Lộc', N'87 Đường Số 3 Kdc Vĩnh Lộc Phường Bình Hưng Hòa B Bình Tân TP.HCM', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000771', N'THPT Việt Âu', N'30/2 Quốc lộ 1A', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000772', N'THPT Việt Nhật', N'371 Nguyễn Kiệm', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000773', N'THPT Hưng Đạo', N'103 Nguyễn Văn Đậu', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000775', N'Trung học Thực hành Đại học Sư phạm', N'280 An Dương Vương Phường 4 Quận 5 Tp. Hồ Chí Minh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000776', N'Phổ thông Năng Khiếu - ĐHQG Tp. HCM', N'153 Nguyễn Chí Thanh', 1,5, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000777', N'THPT Lý Thái Tổ', N'1/22/2a Nguyễn Oanh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000779', N'THPT Trần Quốc Tuấn', N'236/10-12 Thái Phiên', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000780', N'THPT An Dương Vương', N'đường số 3khu phố 6 phường Trường Thọ quận Thủ Đức', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000781', N'THPT Trần Nhân Tông', N'66 Tân Hóa', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000783', N'THPT Đông Dương', N'114/37/12A-E Đường số 10', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000784', N'THPT Phước Kiển', N'Số 1163 Đường Lê Văn Lương Ấp 3', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000785', N'THPT Nhân Việt', N'41-39 Đoàn Hồng Phước', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000786', N'THPT An Nghĩa', N'Ấp An Nghĩa', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000788', N'THPT Phú Lâm', N'12-24 đường số 3 chợ Phú Lâm', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000793', N'THPT Nguyễn Hữu Cảnh', N'845 Hương Lộ 2', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000794', N'THPT Nguyễn Văn Linh', N'Số 02 Đường 3154 Phạm Thế Hiển  Phường 07 Quận 08', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000795', N'Phân hiệu THPT Lê Thị Hồng Gấm', N'147 Pasteur', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000796', N'THPT Nguyễn Thị Diệu', N'12 Trần Quốc Toản', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000797', N'THPT Quốc Trí', N'313 Nguyễn Văn Luông', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000798', N'THPT Vĩnh Viễn', N'73/7 Lê Trọng Tấn - Phường Sơn Kỳ Quận Tân Phú', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A1', N'THPT Bách Việt', N'653 Quốc lộ 13 Kp3', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A2', N'THPT Việt Mỹ Anh', N'252 Lạc Long Quân', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A5', N'THPT Văn Lang', N'02-04 Tân Thành', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A6', N'THPT Bình Hưng Hòa', N'79/19 Đường Số 4 Kp7 P.BHH Q.Bình Tân', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A7', N'THPT Bình Tân', N'117/4H Hồ Văn Long', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A8', N'THPT Nguyễn Tất Thành', N'249C Nguyễn Văn Luông', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007A9', N'THPT Nguyễn Văn Tăng', N'Đường số 1 KP Tái Định Cư Long Bửu', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B0', N'THPT Trần Văn Giàu', N'203/40 Đường Trục Phường 13Quận Bình Thạnh TP.Hồ Chí Minh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B1', N'THPT Phạm Văn Sáng', N'Ấp 3', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B2', N'THPT Đào Sơn Tây', N'53/5 Đường 10 Khu phố 3 Linh Xuân Thủ Đức', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B3', N'THPT Tân Túc', N'C1/3K Khu Phố 3 Đường Bùi Thanh Khiết Thị Trấn Tân Túc Huyện Bình Chánh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B5', N'THPT Thủ Khoa Huân', N'481/8 Trường Chinh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B6', N'THPT Vĩnh Lộc B', N'Đường số 3 Khu Dân Cư Vĩnh Lộc Bxã VĨnh Lộc B huyện Bình Chánh TPHCM', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B7', N'THPT Dương Văn Dương', N'39 Đường số 6 KDC Phú Gia Ấp 2', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007B8', N'THPT Võ Văn Kiệt', N'629 Bình Đông', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007C1', N'THPT Năng khiếu TDTT Huyện Bình Chánh', N'Ấp 1 Mai Bá Hương xã Lê Minh Xuân huyện Bình Chánh', 1,4, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007C2', N'THPT Lê Trọng Tấn', N'Số 5 Đường D2 Phường Sơn Kỳ Quận Tân Phú', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007C3', N'THPT Linh Trung', NULL, 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007C4', N'THPT Dương Văn Thì', NULL, 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007C5', N'THPT Bình Chiểu', NULL, 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007C6', N'THPT Hồ Thị Bi', NULL, 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'790007C7', N'THPT Phong Phú', NULL, 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000802', N'THPT Thủ Thiêm', N'1 Đường Vũ Tông Phan', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000803', N'THPT Ngô Quyền', N'1360 Huỳnh Tấn Phát', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000804', N'THPT Thạnh Lộc', N'đường Nguyễn Thị Sáu - KP1', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000805', N'THPT An Lạc', N'595 Kinh Dương Vương Phường An Lạc Quận Bình Tân', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000806', N'THPT Lê Minh Xuân', N'G11/1 Ấp 7 Xã Lê Minh Xuân H. Bình Chánh', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000807', N'THPT Đa Phước', N'D14/410A QL 50 xã Đa Phước -Huyện Bình Chánh TP.HCM', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000827', N'THPT Đông Đô', N'12B Nguyễn Hữu Cảnh', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000842', N'THPT Nguyễn Hữu Thọ', N'2 Bến Vân Đồn', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000862', N'THPT Minh Đức', N'277 Tân Quý', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000863', N'THPT Thành Nhân', N'69/12 Nguyễn Cửu Đàm P. Tân Sơn Nhì Q. Tân Phú', 2,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000869', N'THPT Lương Thế Vinh', N'131 Cô Bắc', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000875', N'THPT Phạm Phú Thứ', N'425 - 435 Gia Phú', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000F01', N'THPT chuyên Lê Hồng Phong', N'235 Nguyễn Văn Cừ', 1,5, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79000F02', N'THPT chuyên Trần Đại Nghĩa', N'53 Nguyễn Du', 1,5, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79774507', N'THPT Trần Hữu Trang', N'276 Trần Hưng Đạo B', 1,3, 0, N'SGD&DT HCM');
INSERT INTO `school` (matrg, ten, dchi, malh, malt,  maphong, tenso) VALUES (N'79786701', N'THPT Long Thới', N'280 Nguyễn Văn Tạo Ấp 2', 1,3, 0, N'SGD&DT HCM');
